<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>btn_View</name>
   <tag></tag>
   <elementGuidId>870f4c32-8f32-4596-b6ef-eb8efbdcfd4a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#actionItems_renderTableHeaderArray_1705842921199_2_0</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//a[@id='actionItems_renderTableHeaderArray_1705842921199_2_0']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>1855c70d-6a10-4787-bdbd-0e8a5002194d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>javascript:void(0);</value>
      <webElementGuid>57e3d675-0d2d-4f1a-bc21-79ea52c2dfa9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onclick</name>
      <type>Main</type>
      <value>triggerMenuClose('_navBarId_renderTableHeaderArray_1705842921199_2');javascript:viewRecord('1010276', '');return false;</value>
      <webElementGuid>edf59c8f-ac87-4176-9b1f-56af0ec1eb59</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>actionItems_renderTableHeaderArray_1705842921199_2_0</value>
      <webElementGuid>864b3f40-bb07-4e37-8fb2-3d4836c921c1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>View</value>
      <webElementGuid>49d3c780-10b6-4daf-a02a-dd5740210a0c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value> View</value>
      <webElementGuid>9f56b22d-7894-4bc7-88ac-2cbbe28fe9e5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;actionItems_renderTableHeaderArray_1705842921199_2_0&quot;)</value>
      <webElementGuid>9dca5d41-f163-4634-974e-68f4d6e3907f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/04 - Self-services/04.2 - Leave/Page_Home page/iframe_Self services_homePageFrame (1)</value>
      <webElementGuid>cf16b1a1-523c-4958-9189-37be7f7eb284</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//a[@id='actionItems_renderTableHeaderArray_1705842921199_2_0']</value>
      <webElementGuid>277e7fbe-0895-4293-b038-5607e7b6a6b8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>(//table[@id='renderTableHeaderArray']/tbody/tr[3]/td[3]/div/ul/li/a)[2]</value>
      <webElementGuid>cf126a4c-de5b-4f12-8a90-402aeccffc8f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>(//a[contains(text(),'View')])[4]</value>
      <webElementGuid>2d13bfbb-d7e0-45eb-bb71-3a11597d3491</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Toggle Dropdown'])[6]/following::a[1]</value>
      <webElementGuid>7875d0b3-b06f-4894-8f10-8e954eb81d90</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Pending'])[3]/following::a[2]</value>
      <webElementGuid>692702f8-1683-470b-8cc2-8da5ff22bd17</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Casual Leave for 1.0 day On 22-Jan-24 applied on 20/01/2024'])[1]/preceding::a[1]</value>
      <webElementGuid>cb6130bd-c0a1-4d46-8189-446e5fd1ea66</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Pending'])[4]/preceding::a[1]</value>
      <webElementGuid>4adc0f58-d5cf-4439-9497-42c72a8e49da</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>(//a[contains(@href, 'javascript:void(0);')])[7]</value>
      <webElementGuid>3cb9867e-dd84-46ed-85ee-2802ffab203e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/div[2]/div/div/div/table/tbody/tr[3]/td[3]/div/ul/li/a</value>
      <webElementGuid>d0300add-4dae-40e0-b564-57dfbe3c7827</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = 'javascript:void(0);' and @id = 'actionItems_renderTableHeaderArray_1705842921199_2_0' and @title = 'View' and (text() = ' View' or . = ' View')]</value>
      <webElementGuid>39a217b2-230d-4e4c-9f34-852c2a7e635a</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
