<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>btn_Pending</name>
   <tag></tag>
   <elementGuidId>c521bf4a-2505-457b-b0d6-7ba023090ea1</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>tr:nth-of-type(3) > td:nth-of-type(2) > span.li_pending</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//table[@id='renderTableHeaderArray']/tbody/tr[3]/td[2]/span</value>
      </entry>
   </selectorCollection>
   <selectorMethod>CSS</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>52d90320-276b-4d59-b00c-f49da02257fb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>li_pending</value>
      <webElementGuid>23fea9ae-f738-4e2c-b93d-ab7db77f68da</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Pending</value>
      <webElementGuid>2b38bc48-18b7-4f5d-8a76-ec48a9eb8922</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;viewEmpLeaveRequest&quot;)/div[@class=&quot;col-md-12&quot;]/div[@class=&quot;personalprofile&quot;]/div[@id=&quot;renderTable-scroll&quot;]/table[@id=&quot;renderTableHeaderArray&quot;]/tbody[1]/tr[3]/td[2]/span[@class=&quot;li_pending&quot;]</value>
      <webElementGuid>28e2cdcf-ed6f-44e0-98af-30182e4d1312</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/04 - Self-services/04.2 - Leave/Page_Home page/iframe_Self services_homePageFrame (2)</value>
      <webElementGuid>4feb81e7-89a6-43b0-b792-22094fd8b6c3</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//table[@id='renderTableHeaderArray']/tbody/tr[3]/td[2]/span</value>
      <webElementGuid>6dc6ce6b-46e4-4367-a332-ae658bbd3a46</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Casual Leave for 1.0 day On 19-Jan-24 applied on 20/01/2024'])[1]/following::span[1]</value>
      <webElementGuid>76a69937-5b8b-4f85-a466-16f996fe165c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='View'])[2]/following::span[1]</value>
      <webElementGuid>eac15268-a282-4e5d-8a74-75ce9ef71577</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Toggle Dropdown'])[6]/preceding::span[2]</value>
      <webElementGuid>14ee1df3-8017-410c-901c-acad22a738b7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='View'])[3]/preceding::span[3]</value>
      <webElementGuid>5a1b6c0b-0ed0-4d42-9d16-36c87ead99ba</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[3]/td[2]/span</value>
      <webElementGuid>2a811bcd-2ec1-434e-8460-235bd00d2399</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = 'Pending' or . = 'Pending')]</value>
      <webElementGuid>478ecdf1-962b-4656-b2c5-cb4a87e618a1</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
