<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>btn_ViewLeavePolicy</name>
   <tag></tag>
   <elementGuidId>7a41e5dc-fef4-47d6-a749-619dfd2a2ce3</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#secondary_link_showLeavePolicy</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//a[@id='secondary_link_showLeavePolicy']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>c9cd6f01-f6c3-45de-9e1d-f599aa499dfe</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>javascript:void(0);</value>
      <webElementGuid>db86ea39-505e-4803-b291-0472ad61d733</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>secondary_link_showLeavePolicy</value>
      <webElementGuid>aa858b25-42f9-454b-b0f4-43e7669d127a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onclick</name>
      <type>Main</type>
      <value>encryptURLForPanel('mod=MyLeaveDetails&amp;secondaryVar=extendedDwrMode^showLeavePolicy')</value>
      <webElementGuid>7f7d332a-4c2d-4db7-b0d8-dcdac8cdd44e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>button-view</value>
      <webElementGuid>982de542-87fe-4c71-a3f1-16159769d574</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>View Leave Policy</value>
      <webElementGuid>f922a8ce-a3ab-4935-8461-8363c3643965</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;secondary_link_showLeavePolicy&quot;)</value>
      <webElementGuid>a8e0cfa0-e026-4f57-9a32-6e9cd42cc629</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/04 - Self-services/04.2 - Leave/Page_Home page/iframe_Self services_homePageFrame (3)</value>
      <webElementGuid>c29131ed-ca93-4a5f-9163-9da5ffabe75f</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//a[@id='secondary_link_showLeavePolicy']</value>
      <webElementGuid>d6c06f38-d2c4-4485-8b68-fdbf57a469df</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='leaveGroup_getSecondaryLinks']/div[2]/a[3]</value>
      <webElementGuid>a76b6340-aef5-4de5-9997-60d50f5025bf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'View Leave Policy')]</value>
      <webElementGuid>a5137c45-3498-4584-ae41-d8c958ac39e8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Holiday Calendar'])[1]/following::a[1]</value>
      <webElementGuid>1919cb68-19a5-449b-931c-22e8721ee3bc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Leave transactions'])[1]/following::a[2]</value>
      <webElementGuid>6cde8b30-6841-4543-b58e-069f35ec107c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Todays In-Time'])[1]/preceding::a[1]</value>
      <webElementGuid>48e16d4d-983e-4f58-9cfc-459406d36a53</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='View Leave Policy']/parent::*</value>
      <webElementGuid>098d1cf8-735c-4f9d-8177-40564e6cb582</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>(//a[contains(@href, 'javascript:void(0);')])[12]</value>
      <webElementGuid>0fb04970-bca4-4141-b07e-9e766cc0c26c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//a[3]</value>
      <webElementGuid>7599f8f0-c782-46de-8744-f7d5cc959bc0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = 'javascript:void(0);' and @id = 'secondary_link_showLeavePolicy' and (text() = 'View Leave Policy' or . = 'View Leave Policy')]</value>
      <webElementGuid>dd4b005c-bfe5-4867-8851-74844f08a1d4</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
