<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>btn_3dots</name>
   <tag></tag>
   <elementGuidId>ae145bdd-992c-4035-adea-492c27f6d5c9</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#_navBarId_renderTableHeaderArray_1705842921199_2 > span > i.fas.fa-ellipsis-h</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//a[@id='_navBarId_renderTableHeaderArray_1705842921199_2']/span/i</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>i</value>
      <webElementGuid>386a8c90-671c-445d-a6cf-689a6922f3f7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>fas fa-ellipsis-h</value>
      <webElementGuid>0385568d-dc6c-420a-86c5-bdc83805d629</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;_navBarId_renderTableHeaderArray_1705842921199_2&quot;)/span[1]/i[@class=&quot;fas fa-ellipsis-h&quot;]</value>
      <webElementGuid>5dfa68cf-849e-473c-b40d-be9bd8a55953</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/04 - Self-services/04.2 - Leave/Page_Home page/iframe_Self services_homePageFrame (1)</value>
      <webElementGuid>c0b8f010-7936-48f6-ab1d-0cb54e613bf4</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//a[@id='_navBarId_renderTableHeaderArray_1705842921199_2']/span/i</value>
      <webElementGuid>0bd32a31-3b7c-4110-a6d2-4e55322f6559</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/div[2]/div/div/div/table/tbody/tr[3]/td[3]/div/a/span/i</value>
      <webElementGuid>62648fa2-7352-47b5-925c-309f903d7612</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
