<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>menuoption_Self-Service</name>
   <tag></tag>
   <elementGuidId>5c213e7d-dc03-4a6e-90b1-c1afbbc0aac6</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#transact</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='transact']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>c1411327-99cb-444f-a7ba-f4e8f6f5d499</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>transact</value>
      <webElementGuid>73250016-dd74-4af0-9b8e-e419155b0c1f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>v10-side-menu-item </value>
      <webElementGuid>d7bb6a93-8831-4c94-b879-b5adfc3afcaa</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onclick</name>
      <type>Main</type>
      <value>displayURL( 'runet.do?activity=submit&amp;mod=transact');return false;</value>
      <webElementGuid>787a96ea-e1cb-4ee3-ac87-a3511cc1589b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Self services</value>
      <webElementGuid>14027e13-5fe9-46bb-a5d9-9fff1d4408d5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;transact&quot;)</value>
      <webElementGuid>c0a8f9e9-b47a-4770-bd46-d52873cb26f7</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//div[@id='transact']</value>
      <webElementGuid>94f7b162-5237-47a1-a513-f64c846d47d2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='left_side_menus']/div/div[2]</value>
      <webElementGuid>faded3e9-03a1-4168-a784-4cd908e6afcc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Dashboards'])[1]/following::div[1]</value>
      <webElementGuid>a614b4ce-7cae-4cb7-abf4-022ca59d3373</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='×'])[5]/preceding::div[35]</value>
      <webElementGuid>438c5448-d103-472b-a10f-1116f218ab85</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div[2]</value>
      <webElementGuid>681207a6-2032-4019-8e6c-dbed929a01e9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@id = 'transact' and (text() = 'Self services' or . = 'Self services')]</value>
      <webElementGuid>f5e1a0b1-b96d-4394-be4a-570f43dd8cf7</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
