<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>scroll_leaveTransactions</name>
   <tag></tag>
   <elementGuidId>60f0e3c0-871f-46dc-9bcc-daff4fa9258d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#secondary_link_showMyLeaveTransaction</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//a[@id='secondary_link_showMyLeaveTransaction']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>c09db2ce-3fb0-40ce-a7b0-4f238a22866b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>javascript:void(0);</value>
      <webElementGuid>7b16df7d-7c3f-49c6-b4f7-cd2643e077cc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>secondary_link_showMyLeaveTransaction</value>
      <webElementGuid>51ea2b18-846f-47da-80e2-7180a6e00e83</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onclick</name>
      <type>Main</type>
      <value>encryptURLForPanel('mod=MyLeaveDetails&amp;secondaryVar=extendedDwrMode^showMyLeaveTransaction')</value>
      <webElementGuid>04e7666b-7396-4074-909b-80303e49397e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>button-view</value>
      <webElementGuid>19b6d4e0-d98b-4546-99ba-046c590e47a4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Leave transactions</value>
      <webElementGuid>973f1fdb-9e4e-44ce-adb4-f59b8b6b58d6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;secondary_link_showMyLeaveTransaction&quot;)</value>
      <webElementGuid>eeba9dc4-c006-4a76-9ea9-461d4e0e5446</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/04 - Self-services/04.2 - Leave/Page_Home page/iframe_Self services_homePageFrame</value>
      <webElementGuid>41fbd8c2-ed49-4cf3-8afe-846627e8a0f1</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//a[@id='secondary_link_showMyLeaveTransaction']</value>
      <webElementGuid>f17a3103-9a27-4a33-aca4-e79de5f4f74b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='leaveGroup_getSecondaryLinks']/div[2]/a</value>
      <webElementGuid>1010f529-9332-4d1a-a6d9-4a5e203a385b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Leave transactions')]</value>
      <webElementGuid>881dcd34-9e3d-4b2b-bb4f-835925071fe2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='View'])[5]/following::a[1]</value>
      <webElementGuid>654e31da-32a4-4db8-9a12-405d9892fa19</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Toggle Dropdown'])[8]/following::a[2]</value>
      <webElementGuid>1026b416-7187-490d-8ea8-e12f526bc39d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Holiday Calendar'])[1]/preceding::a[1]</value>
      <webElementGuid>14253cc0-d222-4e67-b6e9-cc55487969ba</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='View Leave Policy'])[1]/preceding::a[2]</value>
      <webElementGuid>00d7b1ff-45f0-45b6-ba01-34f0876039db</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Leave transactions']/parent::*</value>
      <webElementGuid>126d0aed-6f3c-433f-9efb-00526419ede3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>(//a[contains(@href, 'javascript:void(0);')])[10]</value>
      <webElementGuid>4795f113-3742-4106-9ed2-7d359af66416</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div[2]/div[4]/div[2]/a</value>
      <webElementGuid>123e7e54-cc0a-4862-b81a-1ac583a66654</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = 'javascript:void(0);' and @id = 'secondary_link_showMyLeaveTransaction' and (text() = 'Leave transactions' or . = 'Leave transactions')]</value>
      <webElementGuid>8abc526f-7261-4f03-aec8-49959517c2b9</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
