<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>VerifyThisOne</name>
   <tag></tag>
   <elementGuidId>3f58bc75-63d7-4c39-9a32-0881bb14773d</elementGuidId>
   <imagePath></imagePath>
   <selectorCollection>
      <entry>
         <key>IMAGE</key>
         <value></value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#viewEmpLeaveRequest > div.col-md-12 > div.personalprofile > #renderTable-scroll > #renderTableHeaderArray > tbody > tr:nth-of-type(3) > td</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>(//td[@onclick='javascript:void(0);'])[11]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>td</value>
      <webElementGuid>81c02e3b-c7b9-4300-9fd0-86c548f489a7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-title</name>
      <type>Main</type>
      <value>Details</value>
      <webElementGuid>4e2c954e-55a7-4e42-8b82-a8c2305c0c67</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onclick</name>
      <type>Main</type>
      <value>javascript:void(0);</value>
      <webElementGuid>4db19f49-62dd-47e9-b2eb-9e3c513973f5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Casual Leave for 1.0 day On 19-Jan-24 applied on 20/01/2024</value>
      <webElementGuid>04dc398e-dadf-4fb0-b425-c190990c7cda</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;viewEmpLeaveRequest&quot;)/div[@class=&quot;col-md-12&quot;]/div[@class=&quot;personalprofile&quot;]/div[@id=&quot;renderTable-scroll&quot;]/table[@id=&quot;renderTableHeaderArray&quot;]/tbody[1]/tr[3]/td[1]</value>
      <webElementGuid>96b9c030-74f1-4c0a-a03f-5220450dc9a1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/04 - Self-services/04.2 - Leave/Page_Home page/iframe_Self services_homePageFrame (2)</value>
      <webElementGuid>2f095acc-dad9-4476-938e-0b4c46585647</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//td[@onclick='javascript:void(0);'])[11]</value>
      <webElementGuid>12859d65-e794-4135-8a53-bb033a4e9ac7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>(//table[@id='renderTableHeaderArray']/tbody/tr[3]/td)[4]</value>
      <webElementGuid>429751cc-8619-4637-8927-fc0d6be5f02c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='View'])[2]/following::td[1]</value>
      <webElementGuid>4790a805-0f3f-466e-b20e-a33fd465a839</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Toggle Dropdown'])[5]/following::td[1]</value>
      <webElementGuid>8618aaf6-f19b-4edd-9138-c4394fdc8b79</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Pending'])[3]/preceding::td[1]</value>
      <webElementGuid>a4f05334-170e-4eeb-a2fd-ed38e1f0d625</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Toggle Dropdown'])[6]/preceding::td[2]</value>
      <webElementGuid>bb9eca63-45ee-481b-95c8-c6b8353075a6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Casual Leave for 1.0 day On 19-Jan-24 applied on 20/01/2024']/parent::*</value>
      <webElementGuid>5a13f938-68c0-48b8-b791-af2b51741687</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/div[2]/div/div/div/table/tbody/tr[3]/td</value>
      <webElementGuid>6ebd1e35-3f94-4cbb-807b-c58e7a3699e6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//td[(text() = 'Casual Leave for 1.0 day On 19-Jan-24 applied on 20/01/2024' or . = 'Casual Leave for 1.0 day On 19-Jan-24 applied on 20/01/2024')]</value>
      <webElementGuid>3ebc3e9c-25b0-474f-87a2-c6b511b796ca</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
