<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>btn_startAttendance</name>
   <tag></tag>
   <elementGuidId>bfa8dd6f-74e0-4542-90a0-4e7e746fdb01</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>a.btn.btn-success</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//a[@onclick=&quot;markTodayAttendance('20/01/2024','1002042','S');return false;&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>9b8494ad-4b67-48c9-87d2-84c52198210f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>#</value>
      <webElementGuid>30f9d579-6ff6-4762-9d8a-b6a6c16ae14d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onclick</name>
      <type>Main</type>
      <value>markTodayAttendance('20/01/2024','1002042','S');return false;</value>
      <webElementGuid>aa012e2b-f7e0-4f8c-983a-1f794556ea9d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>alt</name>
      <type>Main</type>
      <value>Start</value>
      <webElementGuid>39455847-aa2f-4d1b-9937-bd706c124529</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn btn-success</value>
      <webElementGuid>bf3cc9d0-5fad-438c-a4ed-5f85db23ee29</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Start</value>
      <webElementGuid>f342e561-299d-49b2-a079-28617681f8a9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;rightPanelContentSection&quot;)/div[@class=&quot;os-padding&quot;]/div[@class=&quot;os-viewport os-viewport-native-scrollbars-invisible&quot;]/div[@class=&quot;os-content&quot;]/div[@id=&quot;displayPageContent&quot;]/div[@class=&quot;row fullarea&quot;]/div[@class=&quot;col-md-12&quot;]/div[@class=&quot;col-md-5&quot;]/div[@class=&quot;left&quot;]/div[@class=&quot;col-md-12&quot;]/div[@class=&quot;col-md-7&quot;]/div[@class=&quot;simplebar-wrapper&quot;]/div[@class=&quot;simplebar-mask&quot;]/div[@class=&quot;simplebar-offset&quot;]/div[@class=&quot;simplebar-content-wrapper&quot;]/div[@class=&quot;simplebar-content&quot;]/a[@class=&quot;btn btn-success&quot;]</value>
      <webElementGuid>55243f20-948b-4fe8-aaeb-3ab499b449c7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/03 - Dashboard/3.4 - Attendance/Page_Home page/iframe__mycontent-right-frame</value>
      <webElementGuid>56c910a5-f725-4653-a1bf-c340c4a444c5</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//a[@onclick=&quot;markTodayAttendance('20/01/2024','1002042','S');return false;&quot;]</value>
      <webElementGuid>bbdf2a21-4c49-439e-a8ee-5de0614844c2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='displayPageContent']/div[4]/div/div/div/div[2]/div[2]/div/div[2]/div/div/div/a</value>
      <webElementGuid>9679810d-e78b-4898-91f2-fee5ff1709e3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Start')]</value>
      <webElementGuid>4d9b3d1d-3f78-4b90-8984-370dafa5a811</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Attendance entries'])[1]/following::a[1]</value>
      <webElementGuid>055d9f2e-e89a-487e-8437-5e397de57ab4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Regularize attendance'])[1]/preceding::a[1]</value>
      <webElementGuid>7c2aff90-ad16-4b3d-af27-741ae14d2da4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Start']/parent::*</value>
      <webElementGuid>4e0a4400-b768-4e39-ac22-5f9220deebad</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, '#')]</value>
      <webElementGuid>9463e6d2-f837-4573-98df-7a93de20df1f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/a</value>
      <webElementGuid>a631b8f8-031d-4ba0-8579-79a899da9c45</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = '#' and @alt = 'Start' and (text() = 'Start' or . = 'Start')]</value>
      <webElementGuid>29a72efc-b517-4dcd-94b8-1256027908c4</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
