<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_OK</name>
   <tag></tag>
   <elementGuidId>82d1484d-1890-4fe3-9905-933ae4e75812</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#8e0a3b71-5351-497e-9504-a0d056c3beda</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>//*[@id = '8e0a3b71-5351-497e-9504-a0d056c3beda' and (text() = 'OK' or . = 'OK') and @ref_element = 'Object Repository/03 - Dashboard/3.4 - Attendance/Page_Home page/iframe_Self services_homePageFrame']</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>(.//*[normalize-space(text()) and normalize-space(.)='Are you sure you want to mark the close of the day?'])[1]/following::button[1]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>47850aff-ffb3-4a7f-a1cc-3c6ea0cf38e1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn btn-success</value>
      <webElementGuid>5e0ea697-7870-4f5d-a6e2-a1376ec040d7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>8e0a3b71-5351-497e-9504-a0d056c3beda</value>
      <webElementGuid>c79d4ea9-1638-41b8-bab5-2124067ce91f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>OK</value>
      <webElementGuid>a9d64831-7ddf-46eb-80f2-7c1d905bb7dc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;8e0a3b71-5351-497e-9504-a0d056c3beda&quot;)</value>
      <webElementGuid>22eed494-fbff-4675-bd0d-c7dde516be2b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/03 - Dashboard/3.4 - Attendance/Page_Home page/iframe_Self services_homePageFrame</value>
      <webElementGuid>adf99da5-6d09-4155-86d8-ded1914e2ec8</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@id='8e0a3b71-5351-497e-9504-a0d056c3beda']</value>
      <webElementGuid>619ed268-6171-4f82-8c28-ce8513e35d7b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='db4380b7-d790-45b2-87ed-a2877d17494f']/div/div/div[3]/div/div/button</value>
      <webElementGuid>45063fed-8d0f-4fa5-aabe-04c42c5ed9b5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Are you sure you want to mark the close of the day?'])[1]/following::button[1]</value>
      <webElementGuid>2153e4ec-99fb-423d-86e1-edda346fef42</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Confirmation message'])[1]/following::button[1]</value>
      <webElementGuid>9a61a54d-9d1c-4742-ad9d-55beaeb3dc2f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Cancel'])[1]/preceding::button[1]</value>
      <webElementGuid>efd3639a-a7e8-421a-8bd7-892b435e2be9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='OK']/parent::*</value>
      <webElementGuid>022a8882-f0a1-4ae8-8e13-89c4d778ef29</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/div/button</value>
      <webElementGuid>96375437-f8d6-43b6-8443-d9d4ca1c1670</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@id = '8e0a3b71-5351-497e-9504-a0d056c3beda' and (text() = 'OK' or . = 'OK')]</value>
      <webElementGuid>74d1e199-3f04-4ad0-805e-ef7d3b5c3e2a</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
