<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>test_Add break</name>
   <tag></tag>
   <elementGuidId>15e71a41-6afa-4a6f-af97-5c31dd8d976d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>a.attendance-widget-btn</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//a[@onclick=&quot;markTodayAttendanceOnHomepage('24/01/2024','1002042','B');return false;&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>985c18af-645c-4983-89de-ed702e2acbc5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>#</value>
      <webElementGuid>682e8544-095b-49f6-aa20-5fd640c519e0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onclick</name>
      <type>Main</type>
      <value>markTodayAttendanceOnHomepage('24/01/2024','1002042','B');return false;</value>
      <webElementGuid>62831594-35c8-42c6-b61b-dfb599c41d00</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>attendance-widget-btn</value>
      <webElementGuid>fc871614-5ba0-41bd-bf1f-a951e3950fda</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value> Add break   </value>
      <webElementGuid>c009051f-f01d-4d6c-b896-a482ddf61641</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;attendance_content&quot;)/a[@class=&quot;attendance-widget-btn&quot;]</value>
      <webElementGuid>3fafee3d-03fc-41f3-9d27-9dfeb53bbf52</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/03 - Dashboard/3.4 - Attendance/Page_Home page/iframe_Self services_homePageFrame (2)</value>
      <webElementGuid>043e059c-f156-47b6-a3ef-d7bc29e0900e</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//a[@onclick=&quot;markTodayAttendanceOnHomepage('24/01/2024','1002042','B');return false;&quot;]</value>
      <webElementGuid>e8ed3ac4-1ed6-4edd-bea7-bcbedeb1dd13</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='attendance_content']/a</value>
      <webElementGuid>d5083657-a015-49b1-8a63-7e65ce994085</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Total hours'])[1]/following::a[1]</value>
      <webElementGuid>5bc3cd69-49b4-4800-bee2-f6590ccb9bf3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='--'])[1]/following::a[1]</value>
      <webElementGuid>06c10166-1d70-4978-872f-001701de9064</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>(//a[contains(@href, '#')])[11]</value>
      <webElementGuid>a4da15ad-9278-4ebb-95a8-8b77506a5607</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/div[2]/div/a</value>
      <webElementGuid>f605e7e1-86dc-46fb-a9a5-a712f2d786c0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = '#' and (text() = ' Add break   ' or . = ' Add break   ')]</value>
      <webElementGuid>b8f2e6a8-3bc7-4998-995f-3bfa0eaf67e7</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
