<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_TicketID</name>
   <tag></tag>
   <elementGuidId>b3b781d0-3c7d-40e9-8cc9-8bffe347608b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#_selectedSearchOnTicketId</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='_selectedSearchOnTicketId']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>e835fd4f-e52d-413f-8552-7293dd4abdfe</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>_selectedSearchOnTicketId</value>
      <webElementGuid>1a4beac0-8f3e-4177-8e65-bb72cd80c82e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>9646efb6-49b3-49a4-b01f-1ffcff378ea2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>29dcb8d9-e972-4ae2-b693-e4034a23919e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Search on ticket id</value>
      <webElementGuid>ae8d518b-4258-49f6-9db3-bda50ff8e766</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>size</name>
      <type>Main</type>
      <value>50</value>
      <webElementGuid>88296e74-4421-4dd5-a5d5-a058b982b109</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;_selectedSearchOnTicketId&quot;)</value>
      <webElementGuid>1f4596b3-e61b-4a74-9fa0-f8579292627d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/04 - Self-services/04.4 - Tickets/Page_Home page/iframe__mycontent-right-frame</value>
      <webElementGuid>c7f294e7-45fa-470b-b9fd-81e8a9914f28</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='_selectedSearchOnTicketId']</value>
      <webElementGuid>ffa23a08-892d-4b54-9620-a5eeb9d3ff0d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='_filtersOnTicket']/div[2]/div[2]/div[2]/input</value>
      <webElementGuid>2de3e875-dc42-42f6-857d-eeda1bc777f7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div[2]/input</value>
      <webElementGuid>e3c51f3b-bca1-41af-a4e2-3ed7116193b8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = '_selectedSearchOnTicketId' and @type = 'text' and @placeholder = 'Search on ticket id']</value>
      <webElementGuid>ac454e1e-4321-457b-b629-0d3250d9eb71</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
