<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>appear_FoundNothing</name>
   <tag></tag>
   <elementGuidId>2a21f3b7-7b07-44f3-8cbf-877c846bf656</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#ajax_listOfOptions > div</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='ajax_listOfOptions']/div</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>020251fa-1515-44e3-b560-8fa88bf0becb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Oops, nothing found! @emp 15</value>
      <webElementGuid>23df3009-a1cb-4f63-9675-90a3d7971dba</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;ajax_listOfOptions&quot;)/div[1]</value>
      <webElementGuid>4a20163c-deef-4e88-a98c-d8a61ef000f0</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='ajax_listOfOptions']/div</value>
      <webElementGuid>accadd4e-5eb6-4f41-8d2e-3b133e8fad9e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)=concat('id(', '&quot;', 'ajax_listOfOptions', '&quot;', ')/div[1]')])[1]/following::div[2]</value>
      <webElementGuid>83b83466-1a86-4686-b9a7-9bc5c068e922</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Loading...'])[8]/following::div[4]</value>
      <webElementGuid>00298024-0862-4cc2-a0a4-b345118fc44b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Oops, nothing found!']/parent::*</value>
      <webElementGuid>3a87b6bd-607a-4ce1-9955-bbbf35ae01e0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[7]/div</value>
      <webElementGuid>322da3ca-64f5-45d4-a49c-295af274f2ce</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = 'Oops, nothing found! @emp 15' or . = 'Oops, nothing found! @emp 15')]</value>
      <webElementGuid>c77aac9c-f4b0-41df-a854-0d5eb4868097</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
