<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>appear_Profile</name>
   <tag></tag>
   <elementGuidId>b15d0396-6e9c-4460-9abd-447d90559b2d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='runet.do?activity=submit&amp;mod=MyProfileOverview$$panel$$_blank']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>a844f591-f973-4c12-b88b-9c70b45354e9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>runet.do?activity=submit&amp;mod=MyProfileOverview$$panel$$_blank</value>
      <webElementGuid>591828be-00b4-409f-ba13-e38c8eb59cd1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>optionDivSelected</value>
      <webElementGuid>a8c4be7d-361d-451a-ab0e-b1b71d411d7c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>My profile and data</value>
      <webElementGuid>7b53678d-7509-45a9-bbf8-2a3b5df116c1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;runet.do?activity=submit&amp;mod=MyProfileOverview$$panel$$_blank&quot;)</value>
      <webElementGuid>b153d3b0-4af8-4a92-8240-99f6188eac23</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//div[@id='runet.do?activity=submit&amp;mod=MyProfileOverview$$panel$$_blank']</value>
      <webElementGuid>a4ed6471-f718-4228-911a-676250b00709</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='ajax_listOfOptions']/div</value>
      <webElementGuid>a28a9ddd-7044-44a5-a67a-d4119328165d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)=concat('id(', '&quot;', 'runet.do?activity=submit&amp;mod=MyProfileOverview$$panel$$_blank', '&quot;', ')')])[1]/following::div[2]</value>
      <webElementGuid>4ad34a77-94f6-4575-b37c-8868a5245fc8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Loading...'])[7]/following::div[4]</value>
      <webElementGuid>385aba73-54cd-4241-b1ab-5501d4049aa8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='My profile and data']/parent::*</value>
      <webElementGuid>b810a1de-55f8-49fd-9539-3cc8d8662498</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[7]/div</value>
      <webElementGuid>b0ac2cec-f5cc-4d02-b271-92140d3b3c6a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@id = 'runet.do?activity=submit&amp;mod=MyProfileOverview$$panel$$_blank' and (text() = 'My profile and data' or . = 'My profile and data')]</value>
      <webElementGuid>e49304a3-6e49-4973-b02d-d605c1c049e9</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
