<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_View details for emp  04</name>
   <tag></tag>
   <elementGuidId>3c2e8181-5382-4a2d-b14c-33c742c4730f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='runet.do?activity=submit&amp;enc=wsSfF4QuJS+S5O9pkyG05TZ1+gu5nA+ryzi2i%2FBaiBfUTdwAFiKlbJmzfh4FHs+VDEkshu9+QR29KQToVK2nAP3BfEMyqMa48gdtVjWOqHeiCeJV2cu0b0XOQS2v4c9OzOYj7If1wZFu9V4P8WbPaebD5uQsYBEhtaVPaomH4nT33JnqGX4w4FSucEcm60J4gKZ0POd4dQRmWR734F107EHiFcZs7dEPnQXWMkQSlYvVH3wHK6ikOtoL9DH5O+2N$$panel$$_blank']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>1ec2a28d-4ca3-4149-a03f-2ddddae7d0d4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>runet.do?activity=submit&amp;enc=wsSfF4QuJS+S5O9pkyG05TZ1+gu5nA+ryzi2i%2FBaiBfUTdwAFiKlbJmzfh4FHs+VDEkshu9+QR29KQToVK2nAP3BfEMyqMa48gdtVjWOqHeiCeJV2cu0b0XOQS2v4c9OzOYj7If1wZFu9V4P8WbPaebD5uQsYBEhtaVPaomH4nT33JnqGX4w4FSucEcm60J4gKZ0POd4dQRmWR734F107EHiFcZs7dEPnQXWMkQSlYvVH3wHK6ikOtoL9DH5O+2N$$panel$$_blank</value>
      <webElementGuid>61765ddd-3827-4ad4-a300-3e66fa6a3df4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>optionDivSelected</value>
      <webElementGuid>5c8e3ec7-a181-4532-a67d-d0dad889ea52</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>View details for: emp  04 </value>
      <webElementGuid>f8f469dc-86e7-42e2-aa65-1fac486795e0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;runet.do?activity=submit&amp;enc=wsSfF4QuJS+S5O9pkyG05TZ1+gu5nA+ryzi2i%2FBaiBfUTdwAFiKlbJmzfh4FHs+VDEkshu9+QR29KQToVK2nAP3BfEMyqMa48gdtVjWOqHeiCeJV2cu0b0XOQS2v4c9OzOYj7If1wZFu9V4P8WbPaebD5uQsYBEhtaVPaomH4nT33JnqGX4w4FSucEcm60J4gKZ0POd4dQRmWR734F107EHiFcZs7dEPnQXWMkQSlYvVH3wHK6ikOtoL9DH5O+2N$$panel$$_blank&quot;)</value>
      <webElementGuid>7c5aa8c3-0d75-4ef5-928b-e4bb3893b48a</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//div[@id='runet.do?activity=submit&amp;enc=wsSfF4QuJS+S5O9pkyG05TZ1+gu5nA+ryzi2i%2FBaiBfUTdwAFiKlbJmzfh4FHs+VDEkshu9+QR29KQToVK2nAP3BfEMyqMa48gdtVjWOqHeiCeJV2cu0b0XOQS2v4c9OzOYj7If1wZFu9V4P8WbPaebD5uQsYBEhtaVPaomH4nT33JnqGX4w4FSucEcm60J4gKZ0POd4dQRmWR734F107EHiFcZs7dEPnQXWMkQSlYvVH3wHK6ikOtoL9DH5O+2N$$panel$$_blank']</value>
      <webElementGuid>52bb4019-30f8-4c3c-bfc7-c14809d8f82b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='ajax_listOfOptions']/div[4]</value>
      <webElementGuid>dbacb5de-77d5-459c-aba0-7afc24a3f2be</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[7]/div[4]</value>
      <webElementGuid>90f5f221-226f-4270-a34e-7869c58d0707</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@id = 'runet.do?activity=submit&amp;enc=wsSfF4QuJS+S5O9pkyG05TZ1+gu5nA+ryzi2i%2FBaiBfUTdwAFiKlbJmzfh4FHs+VDEkshu9+QR29KQToVK2nAP3BfEMyqMa48gdtVjWOqHeiCeJV2cu0b0XOQS2v4c9OzOYj7If1wZFu9V4P8WbPaebD5uQsYBEhtaVPaomH4nT33JnqGX4w4FSucEcm60J4gKZ0POd4dQRmWR734F107EHiFcZs7dEPnQXWMkQSlYvVH3wHK6ikOtoL9DH5O+2N$$panel$$_blank' and (text() = 'View details for: emp  04 ' or . = 'View details for: emp  04 ')]</value>
      <webElementGuid>ffd37678-6de7-4a29-bd8f-69c292e496df</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
