<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Loading</name>
   <tag></tag>
   <elementGuidId>78c3e9f7-9765-4f5e-a20c-e0f24b128300</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#messageZone</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='messageZone']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>74188b35-e62d-427c-9e24-71bf1723d875</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>messageZone</value>
      <webElementGuid>cb0c3fec-efe7-4ccb-b3aa-ab6e50c0d5cf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ajaxloaderMessageZone</value>
      <webElementGuid>6f96e35a-c811-4eee-b1fb-8c3fab4a4b5a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Loading...</value>
      <webElementGuid>6786423c-80e6-4ee9-bc80-bd4d54cc31a0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;messageZone&quot;)</value>
      <webElementGuid>05c2bf21-4ed8-46ec-ae31-d061cbc12584</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//div[@id='messageZone']</value>
      <webElementGuid>cba616a8-3d8a-4a7d-9744-9aa9e0d1ff0f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='×'])[5]/following::div[8]</value>
      <webElementGuid>af932520-e71c-4227-9bf5-de3687f72df1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Self services'])[1]/following::div[42]</value>
      <webElementGuid>22916a0c-08e4-401e-9df4-cf6550306946</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)=concat('id(', '&quot;', 'messageZone', '&quot;', ')')])[1]/preceding::div[1]</value>
      <webElementGuid>82213881-b838-4fb1-8038-3bc99f3d6a30</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[5]</value>
      <webElementGuid>29ef5a1e-ef09-4dc3-b6ce-4055aab100f5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@id = 'messageZone' and (text() = 'Loading...' or . = 'Loading...')]</value>
      <webElementGuid>3540c3ef-a8fe-452f-b1b9-a1f27eb24823</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
