<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img__modal-content-img-id</name>
   <tag></tag>
   <elementGuidId>8de36bab-671f-4b63-90a4-5e60222b15ab</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#modal-content-img-id</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//img[@id='modal-content-img-id']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>bb6f6e64-b878-49d9-bd52-115fe26a006e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>modal-content-img</value>
      <webElementGuid>18f1a650-81b0-4e26-be74-f80a8abe2fdf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>modal-content-img-id</value>
      <webElementGuid>7293ee2e-c4a3-4e3a-8482-e1d6e3b65001</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>https://images.empxtrack.com/images/client-images/8/pop-up-offer.png</value>
      <webElementGuid>94a082dd-8561-414c-8f40-e46bb37509ee</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;modal-content-img-id&quot;)</value>
      <webElementGuid>d6697a02-9f2a-4127-bb20-e189971123b7</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//img[@id='modal-content-img-id']</value>
      <webElementGuid>499d1810-ef30-4666-bf4d-dab85a7010eb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='img-modal']/div[2]/img</value>
      <webElementGuid>3671a5f4-0700-4235-9b38-8065dc0ccde0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>//img[contains(@src,'https://images.empxtrack.com/images/client-images/8/pop-up-offer.png')]</value>
      <webElementGuid>e1232a5a-c9cd-4725-a27e-943bcf16b98e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/img</value>
      <webElementGuid>eb6820fd-2ec9-4c8d-83f5-790613d74621</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@id = 'modal-content-img-id' and @src = 'https://images.empxtrack.com/images/client-images/8/pop-up-offer.png']</value>
      <webElementGuid>492a95b3-647e-4359-b992-66d512917b38</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
