<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Searchbox</name>
   <tag></tag>
   <elementGuidId>736015b7-52c7-41d7-a602-132a7ad94e44</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#moduleNameId</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='moduleNameId']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>abd87ddb-04ad-45b0-8e42-57871e3cac47</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>moduleName</value>
      <webElementGuid>7c5351d4-6ca3-412d-8610-7e73aa11f310</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>size</name>
      <type>Main</type>
      <value>84px</value>
      <webElementGuid>6aa6a042-12d9-48db-82e3-9099e6512539</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>search-logobar form-control </value>
      <webElementGuid>ebedc334-56cc-4c70-9444-8205b7e311af</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onkeyup</name>
      <type>Main</type>
      <value>ajax_showOptions(this, 'getEmployeesByLetters', event, 'advancedFeatureSearch')</value>
      <webElementGuid>87d5d0c0-b4c1-4c28-8fcd-c65e3e868f1b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>4ce1c0c9-1010-4235-8926-d81eacd16695</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>moduleNameId</value>
      <webElementGuid>747b3372-9918-410a-8b9d-04faad721875</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>2943c3d5-3057-4b41-ac18-d8f72fe75a71</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Search a feature or employee name (@name)</value>
      <webElementGuid>1182bd89-455c-4677-81f9-7887e29e80eb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;moduleNameId&quot;)</value>
      <webElementGuid>f9f345d8-9c56-4f1e-aff5-021540f81386</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='moduleNameId']</value>
      <webElementGuid>5e714fac-7b5c-4e2f-a790-80fa6f31d75a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//ul[@id='cd-primary-nav']/li/div/div/input</value>
      <webElementGuid>da8a4faf-1e9c-4217-ac85-657d1d746e58</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li/div/div/input</value>
      <webElementGuid>9e58afa7-2ef8-4fc0-83b4-264f24371a93</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@name = 'moduleName' and @id = 'moduleNameId' and @type = 'text' and @placeholder = 'Search a feature or employee name (@name)']</value>
      <webElementGuid>c3e93ac3-c073-49ee-af4c-c57654446350</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
