<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>appear_UnrecognizedCompID</name>
   <tag></tag>
   <elementGuidId>ad878c9e-feb6-4f8e-bf1e-3fe72e908086</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#m16_errorMsgOnPopUpEmploginProblem</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='m16_errorMsgOnPopUpEmploginProblem']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>74d25882-a274-4c65-95de-5b552d1041a8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>err</value>
      <webElementGuid>313c9689-b375-48ab-8f7f-ae55c369d53b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>m16_errorMsgOnPopUpEmploginProblem</value>
      <webElementGuid>d0dc2aa2-a98f-4d83-9e0e-291a03fab808</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Company ID (tenant) is not recognized.</value>
      <webElementGuid>9a751aba-bf37-4ec6-9038-8ee75a5cbaf9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;m16_errorMsgOnPopUpEmploginProblem&quot;)</value>
      <webElementGuid>493a1deb-a384-4c75-8168-8d2829d09b7a</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//div[@id='m16_errorMsgOnPopUpEmploginProblem']</value>
      <webElementGuid>88780365-4394-4a16-afc9-ead37fc6620a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='errorMsgOnPopUpEmploginProblem']/div</value>
      <webElementGuid>5886064d-576d-4bfe-84e7-f6811b147b4f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Login problems'])[1]/following::div[2]</value>
      <webElementGuid>f00e1578-071c-42d8-9d65-fdd641c7a15f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Copyright © Saigun Technologies Pvt. Ltd. India. All rights reserved. Confidential'])[1]/following::div[9]</value>
      <webElementGuid>c260c576-c585-4ca6-8ba5-c175b7f3becd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Company ID (tenant) is not recognized.']/parent::*</value>
      <webElementGuid>677bf9d9-6e08-4948-9b3f-31ae38275b6b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div[2]/div</value>
      <webElementGuid>91a936c1-12db-4b28-875c-694252423892</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@id = 'm16_errorMsgOnPopUpEmploginProblem' and (text() = 'Company ID (tenant) is not recognized.' or . = 'Company ID (tenant) is not recognized.')]</value>
      <webElementGuid>967b94f7-2be3-4ed5-90e8-869a13bee630</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
