<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>btn_applyLeave</name>
   <tag></tag>
   <elementGuidId>4962cc8f-9253-456f-b859-f9e240696933</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#btn_Apply</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//a[@id='btn_Apply']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>97284406-dbbf-451a-920f-dfd3de0a727e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn_primary </value>
      <webElementGuid>56e7c82d-a378-4bca-8159-45acf273dd07</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>btn_Apply</value>
      <webElementGuid>eb4584cd-6784-435d-bcea-1332b2a88465</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onclick</name>
      <type>Main</type>
      <value>javascript:applyForLeave('');return false;</value>
      <webElementGuid>25270dea-fe1b-4fb5-90ee-ed7a1ba90574</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Apply</value>
      <webElementGuid>43709408-07b2-45b0-8785-62bcb945a373</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;btn_Apply&quot;)</value>
      <webElementGuid>3ac54c06-3ea2-424d-8463-32e05d1d7734</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/03 - Dashboard/3.3 - Leave/Page_Home page/iframe__mycontent-right-frame</value>
      <webElementGuid>c0495d27-6738-4734-b2a5-65dafc92d61e</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//a[@id='btn_Apply']</value>
      <webElementGuid>736dd200-810e-44d6-8059-a2246efe41f1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='modal-dialog-empxtrack']/div/div/div/div[5]/div/div[2]/ul/li/a</value>
      <webElementGuid>9901fa92-52bc-4c0c-9e0a-ca93dd5bda6f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>(//a[contains(text(),'Apply')])[4]</value>
      <webElementGuid>f57e9ea1-0f5c-4c3a-a6e5-d488f6f1a49a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Step 2. Specify a reason for the leave'])[1]/following::a[1]</value>
      <webElementGuid>58d33d67-7883-4fae-a4c7-1acccca6fb7a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Unapproved'])[1]/following::a[1]</value>
      <webElementGuid>76c3612a-12b7-4508-bf7b-7f234b4628bb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Cancel'])[1]/preceding::a[1]</value>
      <webElementGuid>e5a322a9-8010-481e-8307-166689b1cb1a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='×'])[3]/preceding::a[2]</value>
      <webElementGuid>4338a1d8-1d09-42ce-8785-487bf01e4fb6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[5]/div/div[2]/ul/li/a</value>
      <webElementGuid>23617bce-3e62-486e-ba51-af8ecb9417b4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@id = 'btn_Apply' and (text() = 'Apply' or . = 'Apply')]</value>
      <webElementGuid>bee530ce-63c3-4b37-9b8c-6a5cb2a1404f</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
