<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>btn_SickLeave</name>
   <tag></tag>
   <elementGuidId>97f23d99-e572-42e4-88ca-3c6242919e8d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>tr.last-row > td</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>(//td[@onclick='javascript:void(0);'])[5]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>td</value>
      <webElementGuid>841fbbca-af2c-4d80-98cd-1e49aed7c2ee</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-title</name>
      <type>Main</type>
      <value>Leave type</value>
      <webElementGuid>e41717d6-3978-4bb2-902b-0ddfb71f2c2b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onclick</name>
      <type>Main</type>
      <value>javascript:void(0);</value>
      <webElementGuid>07414230-4f1d-49e9-9ed1-f6c8d9b737f9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Sick Leave</value>
      <webElementGuid>621687fa-7c92-4fc7-af78-2b4dff646e0e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;displayAll&quot;)/div[@class=&quot;col-md-12&quot;]/div[@class=&quot;personalprofile&quot;]/div[@id=&quot;renderTable-scroll&quot;]/table[@id=&quot;renderTableHeaderArray&quot;]/tbody[1]/tr[@class=&quot;last-row&quot;]/td[1]</value>
      <webElementGuid>95acdf7d-ce48-474e-9660-887d924b8c4a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/03 - Dashboard/3.3 - Leave/Page_Home page/iframe__mycontent-right-frame (3)</value>
      <webElementGuid>4ca39a3a-d538-4eaf-ac85-af06f441ce81</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//td[@onclick='javascript:void(0);'])[5]</value>
      <webElementGuid>d69eca7d-4a07-4e62-af7f-5f83380eab7b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//table[@id='renderTableHeaderArray']/tbody/tr[3]/td</value>
      <webElementGuid>1fe878d2-4846-48dd-b9ad-ebe9d39589e1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Apply'])[2]/following::td[1]</value>
      <webElementGuid>6ae5404f-9cc5-4652-975d-2e6cd3118b4c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Toggle Dropdown'])[2]/following::td[1]</value>
      <webElementGuid>506c6dba-480c-4781-9df6-6954dfc8e91a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='-'])[1]/preceding::td[1]</value>
      <webElementGuid>f317b06c-eebb-41a2-aea4-0d9dba4afb8a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Toggle Dropdown'])[3]/preceding::td[2]</value>
      <webElementGuid>c3082825-d1dc-44cb-9490-4c2deffae725</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Sick Leave']/parent::*</value>
      <webElementGuid>0238fc92-8020-410a-b116-7c3334040eae</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[3]/td</value>
      <webElementGuid>906c2e2d-e82a-4233-afe5-a23c88d3891e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//td[(text() = 'Sick Leave' or . = 'Sick Leave')]</value>
      <webElementGuid>870b14c0-38ef-4293-b721-f6ee68f65490</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
