<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>intput_reasonLeave</name>
   <tag></tag>
   <elementGuidId>ae60de2d-b0f8-46e0-97ae-596fa88e4eac</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#reasonForLeave</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//textarea[@id='reasonForLeave']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>textarea</value>
      <webElementGuid>e5bd7795-0710-470a-adc8-2c0b82f170af</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>d3ace837-5e85-495d-ab17-f485ecca3da7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>dataObject.reasonForLeave</value>
      <webElementGuid>1d3aff36-0046-4817-ab81-7345317f09e2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onkeyup</name>
      <type>Main</type>
      <value>textLimit(this, 1000);</value>
      <webElementGuid>49358ca8-0b5e-4be5-9d60-52a2a7e0ac53</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>reasonForLeave</value>
      <webElementGuid>3304f6fc-b1dd-49b5-a052-7f82edf31a0f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Reason for leave</value>
      <webElementGuid>51aae92f-ad23-4c7c-a48e-92720a11a982</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;reasonForLeave&quot;)</value>
      <webElementGuid>b1786950-76c4-4024-b6eb-e76990e67e55</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/03 - Dashboard/3.3 - Leave/Page_Home page/iframe__mycontent-right-frame</value>
      <webElementGuid>7d9e5fd2-2b9b-4a7e-9310-51fc4f371d73</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//textarea[@id='reasonForLeave']</value>
      <webElementGuid>a4b31876-7b63-4e38-9de9-f408e033a7e7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='modal-dialog-empxtrack']/div/div/div/div[2]/div/div[5]/div/div[3]/textarea</value>
      <webElementGuid>9a38a996-9643-4e39-ba17-ec5579ff03ec</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//textarea</value>
      <webElementGuid>c0984726-9654-402c-832c-1d9c125feb26</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//textarea[@name = 'dataObject.reasonForLeave' and @id = 'reasonForLeave' and @placeholder = 'Reason for leave']</value>
      <webElementGuid>3376b9ed-d80a-48dc-a60f-219842a02044</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
