<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>menu_Leave</name>
   <tag></tag>
   <elementGuidId>43860776-a56f-4651-99b6-e49d829f2ef6</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#leaveGroup</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//a[@id='leaveGroup']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>f9312988-8a7e-4ca7-8a62-af0ca80aad01</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>javascript:void(0);</value>
      <webElementGuid>e58a22ef-be99-4bad-ad99-51399ddb529a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>leaveGroup</value>
      <webElementGuid>741a1806-d943-4922-a3fe-65e091011dd4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onclick</name>
      <type>Main</type>
      <value>showHidePanel_v9('menuItems');encryptURLForPanel('runet.do?activity=submit&amp;mod=MyLeaveDetails', '');return false;</value>
      <webElementGuid>ef7ec719-acad-429c-af92-bea751bf756e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Leave</value>
      <webElementGuid>1ad9f1d7-4ff3-4a41-8de1-7ea81eb8e169</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;leaveGroup&quot;)</value>
      <webElementGuid>45b64034-8263-433c-9e3c-36e4431cf776</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//a[@id='leaveGroup']</value>
      <webElementGuid>809fe185-6748-4a7b-bb88-8b8f1f71a8ad</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='menuItemsInner']/div[2]/ul/li[2]/a</value>
      <webElementGuid>490249d1-261c-48a5-8c41-3b402a481ee7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Leave')]</value>
      <webElementGuid>0a2eb5bd-b487-4500-895b-8d653237b1dd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='My profile'])[1]/following::a[1]</value>
      <webElementGuid>81cf8bcb-ac97-49b0-b5b8-a41113d8ca1b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Self services'])[1]/following::a[2]</value>
      <webElementGuid>20d70083-63ce-4cc5-9924-61d14cb9b758</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Attendance'])[1]/preceding::a[1]</value>
      <webElementGuid>c322bb0b-eccb-4bc7-9807-282626d89ee6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Help desk/Tickets'])[1]/preceding::a[2]</value>
      <webElementGuid>3566a1fe-40e3-4434-b8a1-cc1e532173b8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Leave']/parent::*</value>
      <webElementGuid>3198bedb-b8f5-4faf-b006-a15a1d3e7b7e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>(//a[contains(@href, 'javascript:void(0);')])[11]</value>
      <webElementGuid>886715b5-2578-4d37-90b4-7eba997f168d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/ul/li[2]/a</value>
      <webElementGuid>da190f05-9b76-4910-aaac-bb841a381bc7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = 'javascript:void(0);' and @id = 'leaveGroup' and (text() = 'Leave' or . = 'Leave')]</value>
      <webElementGuid>1fd52133-d8de-48bf-a44e-56ae085bf39c</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
