<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>tickbox_StartsHalfDay</name>
   <tag></tag>
   <elementGuidId>a73b0b21-f026-4d28-8386-538d68bea5ac</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#firstHalf</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='firstHalf']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>a98bad7a-dea0-4f4e-a7be-941bd6798509</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>dataObject.firstHalf</value>
      <webElementGuid>91a3e622-e0ce-407b-8884-e46a214529ce</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>dc556b83-4e01-44e6-a202-5849bc15033a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>firstHalf</value>
      <webElementGuid>201cc282-75f1-4de0-bcc5-a5900826a4e8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>checkbox</value>
      <webElementGuid>8d64f519-42ca-4ad7-ae93-d3b1405d204b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onclick</name>
      <type>Main</type>
      <value>javascript:calculateDaysOnCheckBox('');return true;</value>
      <webElementGuid>dec405de-0f11-49d1-b336-fef8b97bfac9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;firstHalf&quot;)</value>
      <webElementGuid>942e296b-d55a-4939-9d34-c5adacc1fb86</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/03 - Dashboard/3.3 - Leave/Page_Home page/iframe__mycontent-right-frame (1)</value>
      <webElementGuid>d2908238-2c47-4e72-8082-6b6cde2a2cd2</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='firstHalf']</value>
      <webElementGuid>2bb222f2-368b-45a4-ba40-82bce4fdd409</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='leaveDetailSection']/div/label/input</value>
      <webElementGuid>4c221e01-370d-4edf-b1ec-595fac13f600</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//label/input</value>
      <webElementGuid>e9dc38b3-dbfb-46cf-bc26-c1be219c3e27</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@name = 'dataObject.firstHalf' and @id = 'firstHalf' and @type = 'checkbox']</value>
      <webElementGuid>962baee7-d337-4dd7-9a78-8d8ebd1ce90b</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
