<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>tickbox_EndHalfDay</name>
   <tag></tag>
   <elementGuidId>a62a62d0-7b3e-4670-aee9-8ca9cbf32642</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#secondHalf</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='secondHalf']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>ebc386f7-c111-4960-aa72-4113ee46cba3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>dataObject.secondHalf</value>
      <webElementGuid>c6ef53d4-8663-4538-bf0d-e762a3f2be39</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>980c27ef-b6d1-4b4d-9994-9d0de203c22c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>secondHalf</value>
      <webElementGuid>24f94ad1-763c-4c3f-b605-907fda567207</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>checkbox</value>
      <webElementGuid>e2e6b47b-10bb-47d4-a3ba-85fb1dc09da9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onclick</name>
      <type>Main</type>
      <value>javascript:calculateDaysOnCheckBox('');return true;</value>
      <webElementGuid>601aea5a-a0c9-4938-a98b-6c07b933ef13</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;secondHalf&quot;)</value>
      <webElementGuid>4698c674-d56a-4149-b2f5-ede5fc073bea</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/03 - Dashboard/3.3 - Leave/Page_Home page/iframe__mycontent-right-frame (1)</value>
      <webElementGuid>35a0717a-017c-4644-a9d7-8b75965eb3d3</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='secondHalf']</value>
      <webElementGuid>cc07b06c-0098-4e1f-a152-93091cf18fd7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='leaveDetailSection']/div[2]/label/input</value>
      <webElementGuid>6716aed2-4a90-41ad-9939-f9e656477f9a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/label/input</value>
      <webElementGuid>bb381191-5abd-4e21-97c6-c5b05900591e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@name = 'dataObject.secondHalf' and @id = 'secondHalf' and @type = 'checkbox']</value>
      <webElementGuid>3a73220a-a9e5-42a5-9c67-0e41fddc3feb</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
