<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Hobbies</name>
   <tag></tag>
   <elementGuidId>be874fd1-eaae-4330-ba1f-5e7dcc2f7e37</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#btn_3</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//a[@id='btn_3']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>b60e7e8b-3b1f-4d45-a4dd-f92484d85bc8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>btn_3</value>
      <webElementGuid>81ea0896-c7f0-471b-b1c5-7f3678c42294</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onclick</name>
      <type>Main</type>
      <value>javascript:triggerPersonalDataModes('AddButtonEmpHobbiesInterestsMethod');return false;</value>
      <webElementGuid>9f897ad0-405e-47bf-97bc-5e61e02c99ac</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Hobbies </value>
      <webElementGuid>6fd99694-f9fe-4f1e-a90c-556bfffbf37f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;btn_3&quot;)</value>
      <webElementGuid>3069910d-e56a-4c9d-8660-79d9e5d970a6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/04 - Self-services/04.1 - Profile/Page_Home page/iframe_Self services_homePageFrame</value>
      <webElementGuid>a80f0069-7aa4-4213-9791-b236516cce12</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//a[@id='btn_3']</value>
      <webElementGuid>79b4b4d9-fa0c-4ab8-8563-0baae4f38853</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='personalDetailsDiv']/div/div/div/div[3]/div[4]/a</value>
      <webElementGuid>40ef323a-c921-4a64-ac20-31e2e979416b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Hobbies')]</value>
      <webElementGuid>62df3dd4-858b-470c-bfa1-c16a344b6e70</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Other details'])[1]/following::a[1]</value>
      <webElementGuid>8a8b5c56-f662-4064-8317-29b8c45eb29f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Beneficiaries'])[2]/following::a[2]</value>
      <webElementGuid>082815a6-b7b9-424d-8278-dc33849234c6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Languages known'])[2]/preceding::a[1]</value>
      <webElementGuid>ef33eba4-8403-4baa-a444-3f178c635139</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Contact details'])[3]/preceding::a[2]</value>
      <webElementGuid>7648308e-38ef-40aa-a89a-a88599247c01</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/a</value>
      <webElementGuid>f4828725-fe25-4e79-ac78-9a029d40e431</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@id = 'btn_3' and (text() = 'Hobbies ' or . = 'Hobbies ')]</value>
      <webElementGuid>67af1371-d8a4-4790-b4e1-6357b9b30530</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
