<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>btn_SelfServices</name>
   <tag></tag>
   <elementGuidId>45b80ac2-605c-4a36-acf4-75baff88393c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#transact_txt</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='transact_txt']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>cd04190e-3bf9-4c81-b821-8ec149ec0478</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>transact_txt</value>
      <webElementGuid>2ef52873-834c-4838-b71f-4ebbc2cb3ea5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>font_text_x-small v10-side-menu-text </value>
      <webElementGuid>54324fde-5fbe-47ac-a75c-767b8ccecb76</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Self services</value>
      <webElementGuid>adccd551-8553-4447-abea-d7ec2de5761d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;transact_txt&quot;)</value>
      <webElementGuid>1f83d736-ffd4-4327-9482-7d8fafac0d3b</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//div[@id='transact_txt']</value>
      <webElementGuid>d861ceb7-f6b4-424c-8ed7-cefe90ef12a7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='transact']/div[2]</value>
      <webElementGuid>ec542efa-0cbe-4829-bdce-607344c26e75</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Dashboards'])[1]/following::div[3]</value>
      <webElementGuid>9146158b-80e5-43e6-8209-6c82ba784b0c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='×'])[5]/preceding::div[33]</value>
      <webElementGuid>c0484533-023f-4510-9884-13b6d1bbfec9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Loading...'])[8]/preceding::div[42]</value>
      <webElementGuid>4b0f0011-48f5-4d42-8395-068a7d6ab0d9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Self services']/parent::*</value>
      <webElementGuid>07f12375-4134-4f2a-b388-896354687636</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div[2]/div[2]</value>
      <webElementGuid>54cb4eef-9ccd-4820-a097-0d41ce3feac0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@id = 'transact_txt' and (text() = 'Self services' or . = 'Self services')]</value>
      <webElementGuid>bbaf2788-b7ef-4581-b32c-262337b4f545</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
