<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Loading</name>
   <tag></tag>
   <elementGuidId>467bd191-b4f4-429d-bc9a-378c4da56116</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#messageZone</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='messageZone']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>1738cd72-f9a1-4cd6-b1ab-b9fa3e24bec9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>messageZone</value>
      <webElementGuid>a9375ecd-7c10-41de-9971-1a8ee7f9503c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ajaxloaderMessageZone</value>
      <webElementGuid>0f87d632-b042-4e46-9335-a59d246d373c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Loading...</value>
      <webElementGuid>3fbfbacc-8b2b-4413-abf0-e7ef3e1a4bbf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;messageZone&quot;)</value>
      <webElementGuid>c283cf1d-4d74-4f7f-879f-b35e01a6e27d</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//div[@id='messageZone']</value>
      <webElementGuid>4ff94efc-9334-4869-9911-efad9be92756</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='×'])[6]/following::div[8]</value>
      <webElementGuid>30f4d239-4222-40f7-8245-62326245ab0c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='×'])[1]/following::div[35]</value>
      <webElementGuid>72d7ea55-a78f-456b-8b9b-fb3ff2736705</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Capture object:'])[1]/preceding::div[1]</value>
      <webElementGuid>bf12fcb8-5303-46ce-a097-768375083915</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Alt'])[1]/preceding::div[1]</value>
      <webElementGuid>b062d819-221e-466a-94f6-2446b05b19a5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[5]</value>
      <webElementGuid>1156af5e-999c-4f96-8f45-a921ccb82016</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@id = 'messageZone' and (text() = 'Loading...' or . = 'Loading...')]</value>
      <webElementGuid>8ecd21ef-9dfa-421e-ad99-ede549c5862a</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
