<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Hobbies</name>
   <tag></tag>
   <elementGuidId>6c30653a-d712-4373-b86e-9e99935d018a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#hobbies0</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='hobbies0']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>986bebc3-3df3-4320-a5e0-5941724ba9af</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>2d6116aa-396e-4615-ac77-e48d3189ca48</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>7802a25a-ef28-44a1-85f1-fabf09611594</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>hobbies0</value>
      <webElementGuid>68e70a45-bb33-4b29-8c27-a61bf6c9e6a3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onkeyup</name>
      <type>Main</type>
      <value>numericFilter(this);return false;</value>
      <webElementGuid>dae4ccde-3200-4c2c-bdd4-462c83f073d9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;hobbies0&quot;)</value>
      <webElementGuid>7cd4d5b5-8368-4ea2-863f-857708c99ec3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/04 - Self-services/04.1 - Profile/Page_Home page/iframe_Self services_homePageFrame</value>
      <webElementGuid>127dc186-53fa-47cf-97e8-0b2df9e7730d</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='hobbies0']</value>
      <webElementGuid>6f08ef68-9d89-4b2a-8b84-5203a894f175</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='modal-dialog-empxtrack']/div/div/div/div[2]/div/div/div[2]/input</value>
      <webElementGuid>322e7e8b-d008-4997-bea5-260ce1d525f5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/div/div/div[2]/div/div/div[2]/input</value>
      <webElementGuid>875d7b2d-30bf-4e18-8c68-5c4459af3f67</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = 'hobbies0']</value>
      <webElementGuid>b464e4e9-4f1a-45c0-92f0-2146a018606a</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
