<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Scroll</name>
   <tag></tag>
   <elementGuidId>31f8f595-efa9-4a5d-93d2-e4b82f07e50c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>div.button-area</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='displayEmpPersonalDetail_getSecondaryLinks']/div[2]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>5b423b48-6ec7-46d4-84e0-a4bd5a86d846</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>button-area</value>
      <webElementGuid>81568a45-a832-4877-b5e4-7f6cbfe5dd7f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>View or Edit Profile  </value>
      <webElementGuid>9edf1bc2-65b4-417c-adb7-42543117aa89</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;displayEmpPersonalDetail_getSecondaryLinks&quot;)/div[@class=&quot;button-area&quot;]</value>
      <webElementGuid>6c3db2ab-09b7-4ae5-8673-125362c9e909</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/04 - Self-services/04.1 - Profile/Page_Home page/iframe_Self services_homePageFrame</value>
      <webElementGuid>6881f5ac-ce6b-4d73-afa4-442fbb2138a1</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='displayEmpPersonalDetail_getSecondaryLinks']/div[2]</value>
      <webElementGuid>3096a0a5-5d26-423e-970d-dd9ebc2a2ccd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='-'])[6]/following::div[6]</value>
      <webElementGuid>237cc7fb-ad2d-4d7a-b941-900e262dcdc4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/div[2]</value>
      <webElementGuid>c9409123-a235-4097-9535-18e64a963fd4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = 'View or Edit Profile  ' or . = 'View or Edit Profile  ')]</value>
      <webElementGuid>99928694-e0ac-4790-9475-81483ae4d8ee</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
