<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Scroll</name>
   <tag></tag>
   <elementGuidId>bf2fe117-c2f5-4074-b6b7-3a4611a906e0</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#renderTableHeaderArray_info</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='renderTableHeaderArray_info']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>9be16fad-9e5b-4308-9002-af33a77bdb29</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>dataTables_info</value>
      <webElementGuid>dd37997b-e12e-4b77-961c-fd6791b94a4d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>renderTableHeaderArray_info</value>
      <webElementGuid>2398f462-332c-4ef5-aca9-48b78ca1e043</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>status</value>
      <webElementGuid>5bcbcbe7-2e12-45db-b608-4829a036fa11</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-live</name>
      <type>Main</type>
      <value>polite</value>
      <webElementGuid>359b5b9c-093d-4c75-b84a-96367647f10e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Showing 1 to 4 of 4 entries</value>
      <webElementGuid>54bdf8ea-c89b-42b7-b3f6-3704c2be9de2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;renderTableHeaderArray_info&quot;)</value>
      <webElementGuid>0c373691-5214-4afa-9800-c6679606b758</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/04 - Self-services/04.4 - Tickets/Page_Home page/iframe_Self services_homePageFrame</value>
      <webElementGuid>d9290f41-7861-4d2a-9f51-f61fa2112cf2</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//div[@id='renderTableHeaderArray_info']</value>
      <webElementGuid>f647e98d-b2a9-40d3-b0a8-7462d4f607dd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='renderTableHeaderArray_wrapper']/div[3]</value>
      <webElementGuid>1516bacf-edfe-419c-8fa5-68290229b4f5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='View details'])[4]/following::div[2]</value>
      <webElementGuid>5f538931-8b16-4319-ac7e-4b171a5c96fe</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Toggle Dropdown'])[4]/following::div[2]</value>
      <webElementGuid>c3a4640f-7a54-4230-b43f-acc355de3d2b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='First'])[1]/preceding::div[1]</value>
      <webElementGuid>a1686ad1-a436-4a43-b0a4-057b7fbd308d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Previous'])[1]/preceding::div[1]</value>
      <webElementGuid>8d55048a-f62f-4c2d-9dab-2adaf8e77256</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Showing 1 to 4 of 4 entries']/parent::*</value>
      <webElementGuid>58882546-9809-475c-bc5c-cf0ac8c3efe4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/div/div[2]/div/div/div/div/div[3]</value>
      <webElementGuid>8bab95e0-bfbf-4955-9973-b46b6c4f856f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@id = 'renderTableHeaderArray_info' and (text() = 'Showing 1 to 4 of 4 entries' or . = 'Showing 1 to 4 of 4 entries')]</value>
      <webElementGuid>c710102a-ef31-426b-aab5-aa1b3ae9f507</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
