<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>btn_Employee</name>
   <tag></tag>
   <elementGuidId>f9cb87b4-815d-4f66-b805-bc8896926609</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#profileImage</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='profileImage']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>6bb3b8f3-2d90-4bfa-bf2a-04f8ddb059ae</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>profileImage</value>
      <webElementGuid>19734649-6a11-4d27-813c-37d0f58432e3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>profileImage</value>
      <webElementGuid>c7a309d9-5cf0-4a5c-9cac-dd8b42131f9b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>e</value>
      <webElementGuid>707b151b-0d80-4955-906e-7920574fc9e4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;profileImage&quot;)</value>
      <webElementGuid>8d9b141e-60c4-4498-95b6-577ab7bba7ca</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//div[@id='profileImage']</value>
      <webElementGuid>44e14c14-e217-4d4f-89f2-f576209685a6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='dropdownMenu1']/div</value>
      <webElementGuid>8436f72a-79c8-4261-833c-d6adca937666</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Employee'])[1]/following::div[3]</value>
      <webElementGuid>ce56fdea-6aee-4d03-b06e-9da83db5fff3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='emp 03'])[1]/following::div[4]</value>
      <webElementGuid>891635c8-0803-4564-98bb-d60a2d8c4141</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='emp 03'])[2]/preceding::div[4]</value>
      <webElementGuid>57a94752-e515-4b58-a4c7-961ead140668</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/div[2]/div/div</value>
      <webElementGuid>93f2ccf3-da94-41ab-8001-d6b63ffedbdd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@id = 'profileImage' and (text() = 'e' or . = 'e')]</value>
      <webElementGuid>0fcc7e79-3992-4f68-9bbe-a1516707b119</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
