<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>btn_AddNewEvent</name>
   <tag></tag>
   <elementGuidId>89fc916c-7e20-4e6b-8f9f-b5e19c8094e1</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#addButton</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//a[@id='addButton']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>e78f1390-2d6b-4fca-8c86-1337f2017a13</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>calendar_content_addEvent</value>
      <webElementGuid>6598cbf4-bb69-4e1a-83ce-5b6bade4b18a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>addButton</value>
      <webElementGuid>f0d823c2-a037-4ba4-9893-682871ebbdf9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>#</value>
      <webElementGuid>70cb53e7-998f-4934-a62b-877273962da5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onclick</name>
      <type>Main</type>
      <value>addNewTaskEvent('2','23-01-2024','-1','','v10Widget');</value>
      <webElementGuid>8728c89d-b135-4aee-ae6f-ea3a8f6becbe</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Add New Event </value>
      <webElementGuid>aa3deb71-4722-46d3-9d74-641a0e10ddd2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;addButton&quot;)</value>
      <webElementGuid>aba00eea-2128-4143-9700-e96cb358fdc6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/03 - Dashboard/3.1 - Event/Page_Home page/iframe_Self services_homePageFrame</value>
      <webElementGuid>cb8f36f5-a1ed-493a-b961-6eda930f745a</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//a[@id='addButton']</value>
      <webElementGuid>e73b7d50-d3e9-43b1-9966-5dca70ec3cf3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='calendar_content']/div/a</value>
      <webElementGuid>85b9f93c-b6a6-44c3-a933-9e2ec3dbc681</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Add New Event')]</value>
      <webElementGuid>ee845a2f-1548-4b24-848d-51c54e2fac7e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='January, 2024'])[1]/following::a[4]</value>
      <webElementGuid>f9069a98-02bf-4a3c-adc9-385f78df7a90</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='You have been credited (Casual Leave) by Testbits Training'])[1]/following::a[6]</value>
      <webElementGuid>0d83be05-cf92-4f76-b901-2854c99f52db</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Select employees:'])[1]/preceding::a[1]</value>
      <webElementGuid>848763f3-ecd6-4aec-8ef8-da5c6e08863f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Go'])[1]/preceding::a[3]</value>
      <webElementGuid>24599913-26fa-4497-8b86-0a1d14d92111</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>(//a[contains(@href, '#')])[8]</value>
      <webElementGuid>586e3945-c148-484b-891e-dd51fd2c6a38</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div[2]/div/div/a</value>
      <webElementGuid>519bf149-e64a-4449-9da9-4006a9ed1c2a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@id = 'addButton' and @href = '#' and (text() = 'Add New Event ' or . = 'Add New Event ')]</value>
      <webElementGuid>6d3d311b-e089-4e4c-a8e1-2dd6f3e5017c</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
