<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_0100</name>
   <tag></tag>
   <elementGuidId>a665711c-e6ef-480a-aac3-7dcaa6ccac11</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='startTime_01:00']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>5a0b6233-bc62-4a34-933a-634bbe397ea9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>timeslot_li_frame</value>
      <webElementGuid>efe3f2a7-51f9-4312-b5da-130b72bdd572</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>startTime_01:00</value>
      <webElementGuid>df13b93b-d590-4935-9091-7679a88ad135</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onclick</name>
      <type>Main</type>
      <value>javascript:updateTimeslot(this.id);return false;</value>
      <webElementGuid>6ac1fbd2-3c40-4d7f-9b42-52a63915ed6b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>01:00</value>
      <webElementGuid>b27683a2-671d-465d-8b48-b2a47904a4ef</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;startTime_01:00&quot;)</value>
      <webElementGuid>711c51a8-2059-4691-95d8-7df36ff918c7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/03 - Dashboard/3.1 - Event/Page_Home page/iframe_Self services_homePageFrame</value>
      <webElementGuid>ed3d97a1-9bf6-4e92-bc0c-f4d2a4929272</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//div[@id='startTime_01:00']</value>
      <webElementGuid>756cdfc5-4451-4c2a-a751-c9a732f68ed2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='eventSection']/div[6]/div/div[3]</value>
      <webElementGuid>48aa3c7d-86df-430a-86d8-794459e91ce4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Start date'])[1]/preceding::div[22]</value>
      <webElementGuid>7e473c1e-ba4b-45ac-a3ad-60e483cb734c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Start time'])[1]/preceding::div[24]</value>
      <webElementGuid>d9ef2e23-f22a-4f07-95cd-ba64f3066e25</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='01:00']/parent::*</value>
      <webElementGuid>18f5359b-5e77-499d-8f00-004b9cc8b73c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/div[6]/div/div[3]</value>
      <webElementGuid>ee91ddeb-2f4d-4ba7-be00-d786a0d90fe6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@id = 'startTime_01:00' and (text() = '01:00' or . = '01:00')]</value>
      <webElementGuid>0bbd62af-59a5-480c-8ab2-719715b792a6</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
