<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Subject</name>
   <tag></tag>
   <elementGuidId>9094ee05-5016-4488-9698-42a6272746a4</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#subject</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='subject']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>51c8631c-bbfc-46a6-b4d8-e1e0076c3ab7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>9f70351d-9d2d-4bce-ae50-8acc56a3a8ed</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>subject</value>
      <webElementGuid>9c366106-317b-4a68-aacd-b7144bf30010</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>72fc2baf-b0a4-4c0e-b5e7-83b3f2ea5de0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;subject&quot;)</value>
      <webElementGuid>d03a7453-2804-444a-91fc-eed238809f7d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/03 - Dashboard/3.1 - Event/Page_Home page/iframe_Self services_homePageFrame</value>
      <webElementGuid>f5fb86e1-b353-4614-a9e5-c5d9a3f080f3</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='subject']</value>
      <webElementGuid>43d0fbd8-413c-4a7b-808b-00ed3994d8c5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='eventSection']/div/div/input</value>
      <webElementGuid>f844093b-a98e-4085-a59c-f887b1cb4022</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/div/div/input</value>
      <webElementGuid>1df39cc0-ee05-42f8-a21d-7a1305c45d8d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = 'subject']</value>
      <webElementGuid>5925abee-8483-4827-a20a-c531fc1b4fec</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
