<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_Location</name>
   <tag></tag>
   <elementGuidId>8092a9a8-5ae7-4dd5-9320-e37d2c157141</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#timeZone</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//select[@id='timeZone']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>59cc25bb-38b0-4779-9754-04c8c48b7993</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>timeZone</value>
      <webElementGuid>67e22990-b734-4681-b76e-cabe38d815ac</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>985983ea-5740-4d39-9e26-4803d45d1fbb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>---Select---(GMT-08:00) Pacific Time (US &amp; Canada)(GMT-07:00) Mountain Time (US &amp; Canada)(GMT-06:00) Central Time (US &amp; Canada)(GMT-05:00) Eastern Time (US &amp; Canada)(GMT+04:00) Abu Dhabi, Muscat(GMT) Greenwhich Mean Time(GMT+05:30) Chennai, Kolkata, Mumbai, New Delhi</value>
      <webElementGuid>60e3ca42-f600-43c6-9280-5be875119fbd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;timeZone&quot;)</value>
      <webElementGuid>205c56c4-fdbf-43d6-bb12-4d7a496ad61d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/03 - Dashboard/3.1 - Event/Page_Home page/iframe_Self services_homePageFrame</value>
      <webElementGuid>27ef4f27-1ae5-43b8-83f7-0d7c662dcfda</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='timeZone']</value>
      <webElementGuid>ff0834aa-7173-4aac-8a6d-b6cdffbb181f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='eventSection']/div[13]/div/select</value>
      <webElementGuid>63b606c0-d814-4d52-a5fc-3cdf4ddbbb0c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Time zone'])[1]/following::select[1]</value>
      <webElementGuid>8e7e501f-6980-4830-bfbf-72e537d9c9be</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Duration'])[1]/following::select[2]</value>
      <webElementGuid>af716a1c-956a-42fd-a344-3ff109e91ea4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Frequency'])[1]/preceding::select[1]</value>
      <webElementGuid>9c85e4ac-aafb-495a-ab85-bcff335e3e4c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[13]/div/select</value>
      <webElementGuid>ee9d95ed-5197-4443-a561-f5ddef963b3e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@id = 'timeZone' and (text() = '---Select---(GMT-08:00) Pacific Time (US &amp; Canada)(GMT-07:00) Mountain Time (US &amp; Canada)(GMT-06:00) Central Time (US &amp; Canada)(GMT-05:00) Eastern Time (US &amp; Canada)(GMT+04:00) Abu Dhabi, Muscat(GMT) Greenwhich Mean Time(GMT+05:30) Chennai, Kolkata, Mumbai, New Delhi' or . = '---Select---(GMT-08:00) Pacific Time (US &amp; Canada)(GMT-07:00) Mountain Time (US &amp; Canada)(GMT-06:00) Central Time (US &amp; Canada)(GMT-05:00) Eastern Time (US &amp; Canada)(GMT+04:00) Abu Dhabi, Muscat(GMT) Greenwhich Mean Time(GMT+05:30) Chennai, Kolkata, Mumbai, New Delhi')]</value>
      <webElementGuid>c9b411b5-74b4-4f51-8c2b-b820d9503943</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
