<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>btn_StartAttendance</name>
   <tag></tag>
   <elementGuidId>eb04a94c-7bae-4018-a29e-341a95a973ac</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>a.btn.btn-success</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//a[@onclick=&quot;markTodayAttendance('21/01/2024', '1002042', 'S');return false;&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>5b8ffedc-62f1-44a4-a27d-4cafe0371a62</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>#</value>
      <webElementGuid>22774edd-5159-4615-a9d4-5089cdb01d81</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onclick</name>
      <type>Main</type>
      <value>markTodayAttendance('21/01/2024', '1002042', 'S');return false;</value>
      <webElementGuid>316edd69-e77d-4604-a7b8-3dd0f0d9ce49</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>alt</name>
      <type>Main</type>
      <value>Start</value>
      <webElementGuid>8c420bf2-2cc4-4d7c-b93c-9a8e00f96c2f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn btn-success</value>
      <webElementGuid>07df76f8-9f67-48c4-b25f-0828bb5a0354</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Start</value>
      <webElementGuid>57751ec1-efa7-4397-9471-bb4039fce318</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;dispMyAttendanceForToday&quot;)/div[@class=&quot;row fullarea&quot;]/div[@class=&quot;height-coloum&quot;]/div[@class=&quot;col-md-12&quot;]/a[@class=&quot;btn btn-success&quot;]</value>
      <webElementGuid>4f5a233e-5f3c-4865-8d74-37ec85834e1d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/04 - Self-services/04.3 - Attendance/Page_Home page/iframe_Self services_homePageFrame</value>
      <webElementGuid>18d90c3e-461d-47a2-9ff5-2c3375007af9</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//a[@onclick=&quot;markTodayAttendance('21/01/2024', '1002042', 'S');return false;&quot;]</value>
      <webElementGuid>ef1a27c0-36ea-43ad-80f0-ef94e91acddb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='dispMyAttendanceForToday']/div/div/div/a</value>
      <webElementGuid>7201b0a1-6f97-4694-9ef7-1011c55ddf5c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Start')]</value>
      <webElementGuid>2b624c59-3ee3-48c9-b191-ef5fa852332a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Todays In-Time'])[1]/following::a[1]</value>
      <webElementGuid>cc5a3e9d-847f-4cc3-850d-26fa0521bee7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='View attendance dashboard'])[1]/preceding::a[1]</value>
      <webElementGuid>959dc005-2e84-4355-8948-c0b3642ae98f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Monthly In-Time Statistics'])[1]/preceding::a[2]</value>
      <webElementGuid>7fe5f5ce-eaab-4389-ae7a-fc2525aa05e5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Start']/parent::*</value>
      <webElementGuid>1557f257-44f5-4a7f-a526-eec2cd987a48</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>(//a[contains(@href, '#')])[2]</value>
      <webElementGuid>b2b83945-b133-460c-b948-25a42231d475</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/div/a</value>
      <webElementGuid>ebdbc0c1-f6a2-43d2-8c4f-c371ab6dba9d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = '#' and @alt = 'Start' and (text() = 'Start' or . = 'Start')]</value>
      <webElementGuid>a6f3c14c-d086-406b-ba44-420fe6c42257</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
