<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>scroll_Attendance</name>
   <tag></tag>
   <elementGuidId>7866683e-40df-44c3-8530-ebd07b7f0561</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>div.height-coloum > div.col-md-12</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='dispMyAttendanceForToday']/div/div/div</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>43c20a5b-7778-40b9-8787-3243ef577f46</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>col-md-12</value>
      <webElementGuid>086ae8f7-5bc7-4aa6-b8c9-d780b5047b2b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Start the attendance for today. Start</value>
      <webElementGuid>29fc13b8-cbd4-452d-8321-b6e8efa0d486</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;dispMyAttendanceForToday&quot;)/div[@class=&quot;row fullarea&quot;]/div[@class=&quot;height-coloum&quot;]/div[@class=&quot;col-md-12&quot;]</value>
      <webElementGuid>b11eaeaa-7c2e-4132-a985-df593260052f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/04 - Self-services/04.3 - Attendance/Page_Home page/iframe_Self services_homePageFrame</value>
      <webElementGuid>86f1b73b-beaa-4450-96e0-a20d324b4cb7</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='dispMyAttendanceForToday']/div/div/div</value>
      <webElementGuid>312d55cd-792b-4420-a95f-8bb26a0bd68d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Todays In-Time'])[1]/following::div[4]</value>
      <webElementGuid>2937231f-6118-45f6-ab4a-b1f2f761988f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='View attendance dashboard'])[1]/preceding::div[2]</value>
      <webElementGuid>b9eb3b3f-e1a8-4848-a693-f55265b36ba3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Monthly In-Time Statistics'])[1]/preceding::div[4]</value>
      <webElementGuid>1a3ea7da-294b-41fe-bbe6-83e5db476e82</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/div[2]/div[2]/div/div/div[2]/div/div/div</value>
      <webElementGuid>b9be8f46-f5fa-4d27-9308-2012a9d294c6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = 'Start the attendance for today. Start' or . = 'Start the attendance for today. Start')]</value>
      <webElementGuid>5073e812-f871-470c-9ca4-c7941dfbce29</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
