<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_End day</name>
   <tag></tag>
   <elementGuidId>100038ec-47f8-4465-ac25-bdad5d18f23d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>span.attendance-widget-endbtn-txt</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='attendance_content']/a[2]/span</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>4ab3f957-a2ee-4162-90b8-bacef75ec89c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>attendance-widget-endbtn-txt</value>
      <webElementGuid>310c81d6-01a3-449d-bf6d-0672f1ce488a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value> End day  </value>
      <webElementGuid>aca698a8-d16d-47bd-bfcc-3423a5bc9440</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;attendance_content&quot;)/a[@class=&quot;attendance-widget-endbtn&quot;]/span[@class=&quot;attendance-widget-endbtn-txt&quot;]</value>
      <webElementGuid>c9f6298f-60fd-4498-b33d-2e0cbce40477</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/04 - Self-services/04.3 - Attendance/Page_Home page/iframe_Self services_homePageFrame (7)</value>
      <webElementGuid>17741fe1-eaf0-4d55-916f-f280a3e80b51</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='attendance_content']/a[2]/span</value>
      <webElementGuid>a1a89d25-bb31-4d7a-8ebe-fb9a8bfb3194</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Total hours'])[1]/following::span[2]</value>
      <webElementGuid>70401413-567e-40de-87e9-ccd3b3b807dc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Leave'])[1]/preceding::span[1]</value>
      <webElementGuid>25dde7a0-8db6-4f00-bfbb-017a0c06fe7b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Loading...'])[1]/preceding::span[1]</value>
      <webElementGuid>35fcfc50-2db9-4920-9972-b186e930d6d5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//a[2]/span</value>
      <webElementGuid>35367dec-81fa-42d1-a7c9-c2554d0df017</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = ' End day  ' or . = ' End day  ')]</value>
      <webElementGuid>a7059211-5a88-49f5-a0ee-228da3317c74</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
