<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>chckbx_LoginDetails</name>
   <tag></tag>
   <elementGuidId>b744c1a2-8559-4d2f-9134-06de1a0e8ce1</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#isPublicComputer</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='isPublicComputer']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>b2e2f75a-0640-40a5-94b8-579b8ddd306a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>checkbox</value>
      <webElementGuid>a6a08bb6-ad25-4007-910b-a8a438eb769a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>isPublicComputer</value>
      <webElementGuid>3171a6bb-1c6e-46d5-bbeb-52ab708d0663</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onclick</name>
      <type>Main</type>
      <value>javascript:setUserDtl();</value>
      <webElementGuid>e36d93d8-1057-4bd8-aca4-b8fef2f2a2f1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;isPublicComputer&quot;)</value>
      <webElementGuid>750b0480-5e6c-4d48-9605-ad0073a6fb85</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='isPublicComputer']</value>
      <webElementGuid>15d874ae-66c6-4962-8970-e8465ef591f1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/input</value>
      <webElementGuid>a9f63af0-24c9-4a90-bc02-cdd6de5d9e42</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'checkbox' and @id = 'isPublicComputer']</value>
      <webElementGuid>0e39d82e-6c9c-4f60-8a87-eec90ce0c98e</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
