<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Username</name>
   <tag></tag>
   <elementGuidId>fea32f3b-659b-48d7-8319-9cea186a2091</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#usr_1</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='usr_1']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>3ebeba35-45c0-4a6c-b6cb-a3baed3b916a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>b1fc2d33-a8f8-46a4-8a5b-dc2a3e1828ff</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>input-box userLogin</value>
      <webElementGuid>1cf77688-d7d3-45e3-9ee0-fb8bf4fa2b87</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>empNo</value>
      <webElementGuid>f74f86bf-97d3-4c41-841e-15c6d45c90b6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>User name</value>
      <webElementGuid>dd08ee16-6b71-41b3-82d2-43896701f07c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onkeypress</name>
      <type>Main</type>
      <value>javascript:detect_Key(event);</value>
      <webElementGuid>7bac9ac1-6d9a-40d7-91a7-d556787e4007</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onfocus</name>
      <type>Main</type>
      <value>document.logonForm.empNo.select();</value>
      <webElementGuid>83d9c4da-848a-4034-8faf-0e0a7ebc349d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>usr_1</value>
      <webElementGuid>d71dd435-2543-4dac-bc15-acf8db370380</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;usr_1&quot;)</value>
      <webElementGuid>a6fea3e5-d0d5-4878-8b9e-5c72fdb432dc</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='usr_1']</value>
      <webElementGuid>28ca731c-ca75-4d48-8c43-beb7be58ace2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/input</value>
      <webElementGuid>3a838009-c0eb-4325-bcf3-f5f79ac3628f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @name = 'empNo' and @placeholder = 'User name' and @id = 'usr_1']</value>
      <webElementGuid>e12f38f3-7370-40df-9341-70220dfe2364</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
