<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>appear_listEmoji</name>
   <tag></tag>
   <elementGuidId>2e3082bb-81ed-499d-8d27-65709a531fed</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#emojiInfo_1000012</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='emojiInfo_1000012']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>8d257a13-e741-4036-bb23-facfb0d15740</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>emoji_des</value>
      <webElementGuid>9c096933-6a8a-490e-b1c7-c79a074b905e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>emojiInfo_1000012</value>
      <webElementGuid>3dc8ba07-2f46-4f49-8b4c-4caca0613ffb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>👌✌👍👏🤝🙏💐🌸🌺🎉🎊🎁😀😁😂😃😄😅😆😇😈😉😊😋😌😍😎😏😐😑😒😓😔😕😖😗😘😙😚😛😜😝😞😟😠😡😢😣😤😥😦😧😨😩😪😫😬😭😮😯😰😱😲😳😴😵😶😷</value>
      <webElementGuid>46736f2c-ad4d-4ca5-9511-e921106d2eb0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;emojiInfo_1000012&quot;)</value>
      <webElementGuid>93c9581c-3de7-4588-8f35-15e2d0eb587d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/03 - Dashboard/3.2 - Feed/Page_Home page/iframe_Self services_homePageFrame (2)</value>
      <webElementGuid>a0dcb952-de6e-4c13-9b88-1ecb11902751</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//div[@id='emojiInfo_1000012']</value>
      <webElementGuid>41a087e0-37de-455e-ac0c-1a9be2091a09</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='emoji']/div[2]</value>
      <webElementGuid>11ba229e-74fd-4391-bda0-91346b08b219</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Warm welcome'])[1]/following::div[13]</value>
      <webElementGuid>9ae3c75f-ca77-4cd7-b3a7-c32d3221393d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[8]/div[2]/div/div[2]</value>
      <webElementGuid>77c09253-5921-4e9f-b66d-7109b3e63a1d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@id = 'emojiInfo_1000012' and (text() = '👌✌👍👏🤝🙏💐🌸🌺🎉🎊🎁😀😁😂😃😄😅😆😇😈😉😊😋😌😍😎😏😐😑😒😓😔😕😖😗😘😙😚😛😜😝😞😟😠😡😢😣😤😥😦😧😨😩😪😫😬😭😮😯😰😱😲😳😴😵😶😷' or . = '👌✌👍👏🤝🙏💐🌸🌺🎉🎊🎁😀😁😂😃😄😅😆😇😈😉😊😋😌😍😎😏😐😑😒😓😔😕😖😗😘😙😚😛😜😝😞😟😠😡😢😣😤😥😦😧😨😩😪😫😬😭😮😯😰😱😲😳😴😵😶😷')]</value>
      <webElementGuid>5ba9d37c-0755-4ad7-a63c-033c2e1e245f</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
