<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>btn_expandCommentsection</name>
   <tag></tag>
   <elementGuidId>db00bfcf-462c-4c66-92b2-99b8c767d7fe</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>i.fas.fa-caret-down</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='display_comments_1000012']/a/i</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>i</value>
      <webElementGuid>3a5809aa-3e6b-464a-ba6f-a0da2693c96a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>fas fa-caret-down</value>
      <webElementGuid>fab66532-0827-4b91-888e-3b753f69968b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;display_comments_1000012&quot;)/a[1]/i[@class=&quot;fas fa-caret-down&quot;]</value>
      <webElementGuid>0de3eae7-d562-4f94-8870-9c40943fc849</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/03 - Dashboard/3.2 - Feed/Page_Home page/iframe_Self services_homePageFrame (1)</value>
      <webElementGuid>6e7fe363-9ce8-4b4e-9cd9-e309f3875924</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='display_comments_1000012']/a/i</value>
      <webElementGuid>0462ad35-c60a-43aa-8fd6-76b4f1b4a652</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[6]/div[2]/a/i</value>
      <webElementGuid>f9da3f5a-6f7e-4a75-ad3e-e1b20e85aca0</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
