<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>btn_addFeed</name>
   <tag></tag>
   <elementGuidId>c0fee965-7dfe-4760-9965-ee66b05f80da</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#btn_3Ci20class3D27fas20fa-plus273E3C2Fi3E26nbsp3BAdd20a20feed</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//a[@id='btn_3Ci20class3D27fas20fa-plus273E3C2Fi3E26nbsp3BAdd20a20feed']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>52d77e72-7712-447a-bc35-f863df586a6d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn_primary </value>
      <webElementGuid>f9083c5a-4a17-4031-b264-03b355ab0330</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>btn_3Ci20class3D27fas20fa-plus273E3C2Fi3E26nbsp3BAdd20a20feed</value>
      <webElementGuid>2e8ec1c3-b9d3-493e-9487-13db003be136</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onclick</name>
      <type>Main</type>
      <value>javascript:feedRoleIssue();return false;</value>
      <webElementGuid>253a02c5-037f-4903-8d11-b7f6bb3afdbe</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value> Add a feed</value>
      <webElementGuid>ffa8a2ce-0e99-467a-a640-aaeef11ff997</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;btn_3Ci20class3D27fas20fa-plus273E3C2Fi3E26nbsp3BAdd20a20feed&quot;)</value>
      <webElementGuid>a48df590-01a9-4b78-8bb5-2501491e5f0c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/03 - Dashboard/3.2 - Feed/Page_Home page/iframe__mycontent-right-frame (2)</value>
      <webElementGuid>15346ad7-8e4b-415f-b679-439c685988cf</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//a[@id='btn_3Ci20class3D27fas20fa-plus273E3C2Fi3E26nbsp3BAdd20a20feed']</value>
      <webElementGuid>aa72b0b4-dbb9-4317-b2cf-c154d1ce0ad6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='content-section-panel']/div/div/div[3]/div/div[2]/ul/li/a</value>
      <webElementGuid>83eb902b-eac8-4fad-b09d-c0881d46425f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Add a feed')]</value>
      <webElementGuid>0720f7b0-c649-4a62-b3cf-8d1c454c1802</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='View more...'])[1]/following::a[1]</value>
      <webElementGuid>1fa38fe2-2cea-4c58-9ba8-afffa1d782b2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='×'])[3]/preceding::a[1]</value>
      <webElementGuid>056c505f-c2a8-492a-8ee4-323da91a6f00</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)=concat('id(', '&quot;', 'btn_3Ci20class3D27fas20fa-plus273E3C2Fi3E26nbsp3BAdd20a20feed', '&quot;', ')')])[1]/preceding::a[1]</value>
      <webElementGuid>60e8d5a9-9df7-4326-a8dd-3c69d63fa44c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li/a</value>
      <webElementGuid>4a2c8060-6731-48eb-931b-4d6c37407687</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@id = 'btn_3Ci20class3D27fas20fa-plus273E3C2Fi3E26nbsp3BAdd20a20feed' and (text() = ' Add a feed' or . = ' Add a feed')]</value>
      <webElementGuid>595cc78d-d6a4-4cb2-a293-74fc1dcbc1f0</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
