<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>btn_LikeUser</name>
   <tag></tag>
   <elementGuidId>d42f6fd0-2c77-46f2-85ad-98fb4accee20</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#fontCls_1000012</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//i[@id='fontCls_1000012']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>i</value>
      <webElementGuid>04cdafe0-a3ba-4bc9-8892-1cd8694d1d31</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>fontCls_1000012</value>
      <webElementGuid>b9924e7f-d5f8-41b2-8819-9a79bcc6bb5f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>far fa-thumbs-up likefeed</value>
      <webElementGuid>883590af-9adc-40b3-bca2-f4ff521b7bb4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;fontCls_1000012&quot;)</value>
      <webElementGuid>9c021a4b-4298-44f8-a0aa-8c1576c82e53</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/03 - Dashboard/3.2 - Feed/Page_Home page/iframe_Self services_homePageFrame (3)</value>
      <webElementGuid>5212b853-d354-408e-918c-21b3b66cc534</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//i[@id='fontCls_1000012']</value>
      <webElementGuid>bac6a130-2f58-4011-99ef-ea775a524c38</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//a[@id='jsFunUpdate_1000012']/i</value>
      <webElementGuid>0df7a929-fb4e-4819-9d7f-8dfc63283240</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[6]/div/a/i</value>
      <webElementGuid>75b7fa5c-590f-4ad7-bcdf-c90749944e17</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//i[@id = 'fontCls_1000012']</value>
      <webElementGuid>29cc24d0-4486-4d62-abb6-1dadc26754d7</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
