<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>i__fas fa-trash-alt</name>
   <tag></tag>
   <elementGuidId>6b9bd395-7e79-4e9e-b07c-45e9e2d5bdfc</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>i.fas.fa-trash-alt</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='viewFeedResponse_1000012_1000011']/div/div[3]/a/i</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>i</value>
      <webElementGuid>95ed690c-beb7-4168-b659-b3da608c3da4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>fas fa-trash-alt</value>
      <webElementGuid>0be318ea-245b-46c8-b83b-83a99b18c1b8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;viewFeedResponse_1000012_1000011&quot;)/div[@class=&quot;col-md-12 comment-del&quot;]/div[@class=&quot;hidden_div&quot;]/a[1]/i[@class=&quot;fas fa-trash-alt&quot;]</value>
      <webElementGuid>ee57a5b5-ac2d-450c-a0fc-2dfa6b79e7ef</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/03 - Dashboard/3.2 - Feed/Page_Home page/iframe_Self services_homePageFrame (2)</value>
      <webElementGuid>e04930af-91a6-49de-b4e5-d73f6c17e76f</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='viewFeedResponse_1000012_1000011']/div/div[3]/a/i</value>
      <webElementGuid>0c7eedb8-67d5-4eae-899e-1152c215e967</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/div/div[3]/a/i</value>
      <webElementGuid>2e28768e-3cbf-412e-84fc-768d60e86010</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
