<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>i_Say hello to emp 10 on joining  as Defaul_35f1c0</name>
   <tag></tag>
   <elementGuidId>90f8affe-31ad-472d-8238-97cee3464914</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>i.fa.fa-paper-plane</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//a[@id='jsFunUpdate_-1']/i</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>i</value>
      <webElementGuid>78547d03-2c29-4892-a371-e4476b9ae8cc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>fa fa-paper-plane</value>
      <webElementGuid>4b3ed2d4-dbe8-4a42-ae11-f353b6eec2ba</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;buddy_box_1000012&quot;)/div[@class=&quot;col-md-12 comment-box&quot;]/div[@class=&quot;col-md-3&quot;]/a[@id=&quot;jsFunUpdate_-1&quot;]/i[@class=&quot;fa fa-paper-plane&quot;]</value>
      <webElementGuid>2a972cd4-f3a6-40d8-b42e-e3e738cbb48e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/03 - Dashboard/3.2 - Feed/Page_Home page/iframe_Self services_homePageFrame (2)</value>
      <webElementGuid>18afea75-0d54-4e1e-842c-8c121cf658b2</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//a[@id='jsFunUpdate_-1']/i</value>
      <webElementGuid>92fffa7d-2c68-440c-8f91-72a020b8617a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[8]/div[2]/a/i</value>
      <webElementGuid>9a34d40e-6b5e-44bc-85b2-f69360633440</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
