<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>iframe__mycontent-right-frame (1)</name>
   <tag></tag>
   <elementGuidId>0f1cc2e9-d1f7-41ec-88df-43ad014fad54</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#mycontent-right-frame</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//iframe[@id='mycontent-right-frame']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>iframe</value>
      <webElementGuid>43fdba37-c722-444d-bf7d-8c8b2b3fdefb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>runet.do?activity=submit&amp;enc=wsSfF4QuJS+S5O9pkyG05Ulig4GmGZIiHumu3zWooNIXh0WR9DlEEf4QQkbh1kTq8EEjGSGIgp93NLybrSpZx1RDWoQwnpFVGW6D58K%2FzdIxXugOrMShYDVLGBJLXKy6XN1HRf9YWA8+p66Tu4GKIgwrPi1xWTAO8MnGjZmVrUH5Ls4C4O7dtZf%2F3ew3pEmTjEX3jwwjAKQ9MZlInmbshqyYONdAlNLQUOIX5sClQ63uXxtS7H6uWOXoJFPuif8Gpgid9mlbpqiEYjZ9c2MgFe7F+Vqde4Et&amp;cdmtHeaderBar=false&amp;showInPanel=true</value>
      <webElementGuid>bec7d9f3-7789-4a9b-99ce-cb21863a3f04</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>mycontent-right-frame</value>
      <webElementGuid>1c037edc-36b0-49e1-8b6e-8babb886e3a2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>mycontent-right-frame</value>
      <webElementGuid>26aff786-c937-4436-b73e-899e4ac13f15</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>mycontent-right-frame</value>
      <webElementGuid>510ec90e-4a0f-4e30-90a4-c18fa07bb5b7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>width</name>
      <type>Main</type>
      <value>100%</value>
      <webElementGuid>2c5a23ee-be8e-4bb9-881d-094d88135ce3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>height</name>
      <type>Main</type>
      <value>95%</value>
      <webElementGuid>334454da-9b04-4ecc-9bb8-861d3a424691</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;mycontent-right-frame&quot;)</value>
      <webElementGuid>835e3a87-12f5-4929-b141-9eab1f636d2d</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//iframe[@id='mycontent-right-frame']</value>
      <webElementGuid>821c69e8-db9c-40da-a332-677dc9655261</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='mycontent-right']/iframe</value>
      <webElementGuid>7bccfaf3-2986-42a2-83d3-df55476ae572</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div[3]/iframe</value>
      <webElementGuid>ff29765e-f946-4c38-8ca1-19cb2c9e3d02</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//iframe[@src = 'runet.do?activity=submit&amp;enc=wsSfF4QuJS+S5O9pkyG05Ulig4GmGZIiHumu3zWooNIXh0WR9DlEEf4QQkbh1kTq8EEjGSGIgp93NLybrSpZx1RDWoQwnpFVGW6D58K%2FzdIxXugOrMShYDVLGBJLXKy6XN1HRf9YWA8+p66Tu4GKIgwrPi1xWTAO8MnGjZmVrUH5Ls4C4O7dtZf%2F3ew3pEmTjEX3jwwjAKQ9MZlInmbshqyYONdAlNLQUOIX5sClQ63uXxtS7H6uWOXoJFPuif8Gpgid9mlbpqiEYjZ9c2MgFe7F+Vqde4Et&amp;cdmtHeaderBar=false&amp;showInPanel=true' and @id = 'mycontent-right-frame' and @name = 'mycontent-right-frame']</value>
      <webElementGuid>9194a3d8-f413-4afe-9ab8-3a3e9ee1a24b</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
