<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>iframe__mycontent-right-frame</name>
   <tag></tag>
   <elementGuidId>e6fc2a5d-fb5e-4791-9b44-523641f5bbcf</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#mycontent-right-frame</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//iframe[@id='mycontent-right-frame']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>iframe</value>
      <webElementGuid>c2c77812-00eb-4fad-bd7c-cc242fdeac15</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>runet.do?activity=submit&amp;enc=wsSfF4QuJS+S5O9pkyG05Ulig4GmGZIiHumu3zWooNIXh0WR9DlEEf4QQkbh1kTq8EEjGSGIgp93NLybrSpZx1RDWoQwnpFVGW6D58K%2FzdIxXugOrMShYDVLGBJLXKy6XN1HRf9YWA8+p66Tu4GKIgwrPi1xWTAO8MnGjZmVrUH5Ls4C4O7dtZf%2F3ew3pEmTjEX3jwwjAKQ9MZlInmbshqyYONdAlNLQUOIX5sClQ63uXxtS7H6uWOXoJFPuif8Gpgid9mlbpqiEYjZ9c2MgFe7F+Vqde4Et&amp;cdmtHeaderBar=false&amp;showInPanel=true</value>
      <webElementGuid>26f73a7b-63cf-4414-adab-3314f3753828</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>mycontent-right-frame</value>
      <webElementGuid>d1ca0afc-4c95-45b0-acbe-bd9bbc5aea9b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>mycontent-right-frame</value>
      <webElementGuid>452b0b74-fd73-46d7-9979-e680a67c1267</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>mycontent-right-frame</value>
      <webElementGuid>d5ba250b-3561-4b69-8271-6b145af1e8db</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>width</name>
      <type>Main</type>
      <value>100%</value>
      <webElementGuid>a50c10c3-b4d1-4147-9118-dbb5b42265f4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>height</name>
      <type>Main</type>
      <value>95%</value>
      <webElementGuid>edf9c68d-0f09-4320-b190-ce8b7ba3d732</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;mycontent-right-frame&quot;)</value>
      <webElementGuid>760f3fc3-4bf8-4aee-86c5-c051a1b69316</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//iframe[@id='mycontent-right-frame']</value>
      <webElementGuid>b6e94791-6964-49d7-ade3-80b2fc1285e8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='mycontent-right']/iframe</value>
      <webElementGuid>6b9db241-10bf-4c2c-8a37-033a4a90f279</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div[3]/iframe</value>
      <webElementGuid>06d49751-6a00-4d64-b789-02f03a4ccc38</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//iframe[@src = 'runet.do?activity=submit&amp;enc=wsSfF4QuJS+S5O9pkyG05Ulig4GmGZIiHumu3zWooNIXh0WR9DlEEf4QQkbh1kTq8EEjGSGIgp93NLybrSpZx1RDWoQwnpFVGW6D58K%2FzdIxXugOrMShYDVLGBJLXKy6XN1HRf9YWA8+p66Tu4GKIgwrPi1xWTAO8MnGjZmVrUH5Ls4C4O7dtZf%2F3ew3pEmTjEX3jwwjAKQ9MZlInmbshqyYONdAlNLQUOIX5sClQ63uXxtS7H6uWOXoJFPuif8Gpgid9mlbpqiEYjZ9c2MgFe7F+Vqde4Et&amp;cdmtHeaderBar=false&amp;showInPanel=true' and @id = 'mycontent-right-frame' and @name = 'mycontent-right-frame']</value>
      <webElementGuid>0d6cc59e-715b-406b-a2ac-23aa790ba837</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
