<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>iframe_Manager services_homePageFrame</name>
   <tag></tag>
   <elementGuidId>3b2cd586-d094-4d6a-9f7b-8d37eac8ae52</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#homePageFrame</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//iframe[@id='homePageFrame']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>iframe</value>
      <webElementGuid>fc171c03-c42a-4743-877f-39280581fcae</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>runet.do?activity=submit&amp;enc=wsSfF4QuJS+S5O9pkyG05TZ1+gu5nA+ryzi2i%2FBaiBdUFDXpThWC3B+7y60b6oPaWcSp2oTaYHT7XIl8hsJFEMoT5xKz7rWCmm98XBirJGaMYtbEkBoSra8p0bqpWijYx9okq%2FKQ7WsJyBT9oQ1O+sJGJR7NcsOm8D5hwi8WTeVuj772PwqrT3d0VCO2uHEh</value>
      <webElementGuid>26f58573-acc6-45d6-8cb0-65bb0dedddbd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>homePageFrame</value>
      <webElementGuid>494328d4-d5ca-40e2-a9c9-15939eaef7a8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>overlay_homePageFrame</value>
      <webElementGuid>ef899487-8b37-4c41-a0e8-135dfaf467b3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>homePageFrame</value>
      <webElementGuid>11292acf-abdc-4c81-9131-d290a66a23cf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;homePageFrame&quot;)</value>
      <webElementGuid>14bef4bd-53ab-4a40-a5d5-c964f5127270</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//iframe[@id='homePageFrame']</value>
      <webElementGuid>39ee3732-4c6d-4cdd-8183-98de1f0f2d70</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='content-section']/iframe</value>
      <webElementGuid>4a77a209-dd8d-4f7a-afaa-01b865237c36</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//iframe</value>
      <webElementGuid>b11214bf-0062-4bb5-a61c-5b5b32e74523</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//iframe[@src = 'runet.do?activity=submit&amp;enc=wsSfF4QuJS+S5O9pkyG05TZ1+gu5nA+ryzi2i%2FBaiBdUFDXpThWC3B+7y60b6oPaWcSp2oTaYHT7XIl8hsJFEMoT5xKz7rWCmm98XBirJGaMYtbEkBoSra8p0bqpWijYx9okq%2FKQ7WsJyBT9oQ1O+sJGJR7NcsOm8D5hwi8WTeVuj772PwqrT3d0VCO2uHEh' and @id = 'homePageFrame' and @name = 'homePageFrame']</value>
      <webElementGuid>b090b55b-d1a0-4882-b813-c26a0c307594</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
