<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>iframe_Self services_homePageFrame (4)</name>
   <tag></tag>
   <elementGuidId>effa0778-f1ce-4d4d-9b98-6010634af5e9</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#homePageFrame</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//iframe[@id='homePageFrame']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>iframe</value>
      <webElementGuid>7928de9f-7662-4f5e-85f4-55d03fa9f15c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>runet.do?activity=submit&amp;enc=c7rx7N8xkXknprpz06dlP2J%2FdJEzP4ngFbARIA2bIHenwFJJ7suSW+ATSBCWtA0VeFp8us9jRHmZeyi78fc7sw%3D%3D</value>
      <webElementGuid>19f3d418-00c9-40fd-a82a-b9ec60dfb622</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>homePageFrame</value>
      <webElementGuid>14b580b6-7540-4f6b-86e8-669bafcea764</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>overlay_homePageFrame</value>
      <webElementGuid>26f2e5e0-1987-4b3a-8e10-36910fa08127</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>homePageFrame</value>
      <webElementGuid>cf0c9a71-40c6-4ae2-9be6-679186c899d8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;homePageFrame&quot;)</value>
      <webElementGuid>a68cf08d-7e31-4c85-9c9a-4a61a2c6e26b</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//iframe[@id='homePageFrame']</value>
      <webElementGuid>f9a79a87-84e0-4165-bf9f-8b8909d78650</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='content-section']/iframe</value>
      <webElementGuid>e7bb7f55-1216-419c-a583-8b0eba5dec9e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//iframe</value>
      <webElementGuid>830c346a-0b4d-4ec3-af76-13d77a21c01e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//iframe[@src = 'runet.do?activity=submit&amp;enc=c7rx7N8xkXknprpz06dlP2J%2FdJEzP4ngFbARIA2bIHenwFJJ7suSW+ATSBCWtA0VeFp8us9jRHmZeyi78fc7sw%3D%3D' and @id = 'homePageFrame' and @name = 'homePageFrame']</value>
      <webElementGuid>4cadeed6-2a05-4715-a10f-b505701e0cd3</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
