<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Say hello to emp 10 on joining  as De_b8626a</name>
   <tag></tag>
   <elementGuidId>033f9449-a788-4476-8c92-132720a9d828</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#_reponse_note_1000012</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='_reponse_note_1000012']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>7b34a49b-3428-4100-b257-62f16849f37a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>0c039f45-bee6-450b-b3b5-3d9647182f6a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>_reponse_note_1000012</value>
      <webElementGuid>647969ee-5b31-4bd9-aa5a-2c20e85f9990</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>89c4f3c3-0065-4b5c-a25e-e62c6730e1f4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Enter your comment</value>
      <webElementGuid>7a427aea-e77a-432f-84ce-9b5874a9ec9e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;_reponse_note_1000012&quot;)</value>
      <webElementGuid>9cf1377b-264b-437a-ade4-53b91e503bd5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/03 - Dashboard/3.2 - Feed/Page_Home page/iframe_Self services_homePageFrame (2)</value>
      <webElementGuid>71ae7702-179f-4d8b-a27f-a1580dd1daeb</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='_reponse_note_1000012']</value>
      <webElementGuid>05b5f02b-6736-4b51-9d62-54f0fb91020f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='buddy_box_1000012']/div[8]/div/div/input</value>
      <webElementGuid>57bdae62-e06a-45db-bf50-dd104bdd7df7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[8]/div/div/input</value>
      <webElementGuid>e8dcbd5e-d724-4bb3-917e-0e43f07fb8ef</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = '_reponse_note_1000012' and @placeholder = 'Enter your comment']</value>
      <webElementGuid>797f15b3-7e78-4a21-a555-861f07a8b679</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
