<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Comment</name>
   <tag></tag>
   <elementGuidId>36b78ab1-0572-442c-b369-95e2014b76b3</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#_reponse_note_1000012</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='_reponse_note_1000012']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>0a83b091-ae42-4c5c-9c8c-4bdb84075c78</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>294424fa-70ca-4047-a7f8-4c44ed289889</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>_reponse_note_1000012</value>
      <webElementGuid>386bada3-1ce4-44f3-a330-727e513e9f2f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>c71c4784-51db-4993-8280-0f9a93fd67f8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Enter your comment</value>
      <webElementGuid>7510c3df-2a26-4294-a136-ccabefd14964</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;_reponse_note_1000012&quot;)</value>
      <webElementGuid>74ab718f-5f8e-418a-8107-478a8f8897b4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/03 - Dashboard/3.2 - Feed/Page_Home page/iframe_Self services_homePageFrame</value>
      <webElementGuid>6a8400b2-7ee3-415c-b9a3-f3fe2cd19317</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='_reponse_note_1000012']</value>
      <webElementGuid>158788e0-0540-487f-8996-cbb08b3fc78d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='buddy_box_1000012']/div[8]/div/div/input</value>
      <webElementGuid>051e62a8-f831-4c6f-a7b4-224b403008b6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[8]/div/div/input</value>
      <webElementGuid>64efb11a-ded1-4424-a197-3d36071ed615</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = '_reponse_note_1000012' and @placeholder = 'Enter your comment']</value>
      <webElementGuid>010145cc-161f-4cb6-8038-32d6a9d1d718</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
