<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>listEmoji_Hibiscus</name>
   <tag></tag>
   <elementGuidId>e640b584-03df-42e6-8b86-3f08b81f1e06</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>a[title=&quot;HIBISCUS&quot;] > span</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='help-header_1000012']/div/div[9]/a/span</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>e3c8db8b-a929-417a-bb40-50475191d227</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>🌺</value>
      <webElementGuid>6138cf67-deb3-455c-8c64-da2f637dc658</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;help-header_1000012&quot;)/div[@class=&quot;col-md-12&quot;]/div[@class=&quot;col-md-2&quot;]/a[1]/span[1]</value>
      <webElementGuid>67789708-2a98-459d-8616-97a07c3a1c67</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/03 - Dashboard/3.2 - Feed/Page_Home page/iframe_Self services_homePageFrame (2)</value>
      <webElementGuid>e839d06d-9c04-4443-b6d6-8c1d424fc84e</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='help-header_1000012']/div/div[9]/a/span</value>
      <webElementGuid>87ce8bc4-08a3-4c9f-bc4f-e0b9843bc1dc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='🌸'])[1]/following::span[1]</value>
      <webElementGuid>aec002dd-f5ec-47b8-a89f-93b5ca4466bc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='💐'])[1]/following::span[2]</value>
      <webElementGuid>8ef4473c-96e9-4906-833b-ddb286965c8e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='🎉'])[1]/preceding::span[1]</value>
      <webElementGuid>f1d63207-5e55-4e3a-86ea-93c17c1767a3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='🎊'])[1]/preceding::span[2]</value>
      <webElementGuid>8776403e-808b-419f-9679-d41d7101b710</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='🌺']/parent::*</value>
      <webElementGuid>61ed509d-8eaf-4bdd-8d5b-c8543a9e603a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[9]/a/span</value>
      <webElementGuid>35456982-0e7e-4af5-b549-925ce9a19e43</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = '🌺' or . = '🌺')]</value>
      <webElementGuid>e7880d89-00a1-44ef-8a8e-5c6f4b3cba17</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
