<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Send message</name>
   <tag></tag>
   <elementGuidId>24ab6f9b-2622-4e7c-a4b7-e3eca6cdd6f2</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#btn_Send20message</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//a[@id='btn_Send20message']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>c14333ad-f4e2-4d30-b9aa-61f34aa1c362</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn_primary </value>
      <webElementGuid>36f1115d-619a-4c66-be2d-50d1099ad91b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>btn_Send20message</value>
      <webElementGuid>4fef9820-31b6-45a9-9df4-039a828ac179</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onclick</name>
      <type>Main</type>
      <value>javascript:sendChatMessageToSelectedEmployee_v9();return false;</value>
      <webElementGuid>98f2652c-7a7c-4d98-9ed0-ac812de1c74c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Send message</value>
      <webElementGuid>6b060894-3621-4242-8c9c-c073615b9730</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;btn_Send20message&quot;)</value>
      <webElementGuid>1e2c2021-f227-4b52-a253-5ceedbbe1fbd</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//a[@id='btn_Send20message']</value>
      <webElementGuid>e45c33b8-3e5c-4405-96c9-6a27b05e6b3e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='modal-dialog-empxtrack']/div/div/div/div[5]/div/div[2]/ul/li/a</value>
      <webElementGuid>155e36dc-a943-4c42-8392-00cd75ff9175</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Send message')]</value>
      <webElementGuid>e669bf24-91a4-4766-9016-3fd8e53ca9f5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Message'])[1]/following::a[1]</value>
      <webElementGuid>006ba7fd-72a6-46f9-817c-d5c0ec8f3c39</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Select employee'])[1]/following::a[1]</value>
      <webElementGuid>feded2fd-8f17-42bc-a340-eb9314ea9e91</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Close'])[1]/preceding::a[1]</value>
      <webElementGuid>60b89cbd-ba87-4c99-9102-e4ac107ec766</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='×'])[5]/preceding::a[2]</value>
      <webElementGuid>4fcfb4a2-9dd1-44a6-ab02-17bfc3369e3a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Send message']/parent::*</value>
      <webElementGuid>94179c15-45dc-4502-aefe-4a1ee7b57bfe</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[5]/div/div[2]/ul/li/a</value>
      <webElementGuid>578cffb3-dc63-4164-ad7c-9a8605a62587</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@id = 'btn_Send20message' and (text() = 'Send message' or . = 'Send message')]</value>
      <webElementGuid>c837037f-b6bf-41db-b6d1-c0705c6ff5f0</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
