<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Submit</name>
   <tag></tag>
   <elementGuidId>99a55560-df9f-4e55-ad50-6ddf391ec80e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#btn_Submit</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//a[@id='btn_Submit']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>beb7f093-2f75-4528-aa40-880b8fc72f46</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn_primary </value>
      <webElementGuid>d0083dc2-e775-45c2-86ed-bef17a2b540b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>btn_Submit</value>
      <webElementGuid>f8ee78f1-c4e0-4906-86ad-028f1d6ebe4b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onclick</name>
      <type>Main</type>
      <value>javascript:savePollResult_v9('0');return false;</value>
      <webElementGuid>ea920173-4869-4e85-b30f-8fd43e9d69c1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Submit</value>
      <webElementGuid>2c3a6ee1-66de-4a34-bd55-fad5214b293e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;btn_Submit&quot;)</value>
      <webElementGuid>1570ca48-bf77-4969-922e-75d80bf8b3a7</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//a[@id='btn_Submit']</value>
      <webElementGuid>49fa4426-476c-473f-be96-3518bbb8508e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='modal-dialog-empxtrack']/div/div/div/div[5]/div/div[2]/ul/li/a</value>
      <webElementGuid>96438610-9efd-48d2-bf7c-350cd15316bd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Submit')]</value>
      <webElementGuid>6363cefe-449e-41c4-a087-e150688490e2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Close'])[1]/preceding::a[1]</value>
      <webElementGuid>4cb4d955-2d84-4bd1-8e9e-4a2d69249b38</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='×'])[5]/preceding::a[2]</value>
      <webElementGuid>ec56f98e-168a-462f-85a5-bf1f834d16ea</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Submit']/parent::*</value>
      <webElementGuid>ea5992e9-ae95-47e7-8b83-53874c802173</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[5]/div/div[2]/ul/li/a</value>
      <webElementGuid>874b3c74-1a51-4cd6-b558-6660b6ef9579</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@id = 'btn_Submit' and (text() = 'Submit' or . = 'Submit')]</value>
      <webElementGuid>1ce8928f-a6ab-4b6b-8cc8-f725ca2d2500</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
