<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>clickpulseRating_4</name>
   <tag></tag>
   <elementGuidId>da48aa0f-f570-4290-b1d1-a6d572ef9302</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#pulseRating_4</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//img[@id='pulseRating_4']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>1f86c0bc-2745-4962-90af-d80f1c918d1e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>images/client/tenant-lite/blankStarRating.gif</value>
      <webElementGuid>2221a7f4-a565-46f6-956a-5f451b448478</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>5.0</value>
      <webElementGuid>9d6a5594-c723-4336-b553-34a3b1f0e1d2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>pulseRating_4</value>
      <webElementGuid>058bd501-2777-436c-b090-5c1d40025439</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onclick</name>
      <type>Main</type>
      <value>changeStarRatingOptions('pulseRating','4','5','5.0');setChanged();</value>
      <webElementGuid>a69ef72d-c9d2-48b9-ba53-dbc530a5d6ee</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;pulseRating_4&quot;)</value>
      <webElementGuid>5e10c159-213d-4500-87f2-2fa2a2db0886</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//img[@id='pulseRating_4']</value>
      <webElementGuid>644c3b84-00a2-4d65-a5f6-50eeb56d20d3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='modal-dialog-empxtrack']/div/div/div/div[2]/div[2]/div/div[3]/div/img[5]</value>
      <webElementGuid>db304aa5-ac80-45ff-91b5-ddb2c429b6a7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>//img[@title='5.0']</value>
      <webElementGuid>5aac3344-3a12-43f4-a10a-057478d20103</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//img[5]</value>
      <webElementGuid>17884cf4-469b-426b-8fb0-3f85e8485025</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@src = 'images/client/tenant-lite/blankStarRating.gif' and @title = '5.0' and @id = 'pulseRating_4']</value>
      <webElementGuid>6909b08e-d03c-4b53-b1a2-ffd5d4ca2879</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
