<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_emp  01</name>
   <tag></tag>
   <elementGuidId>c613ecbb-e675-4a7d-b898-215917820ae9</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#1001194</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='1001194']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>4a125e11-6268-4b40-ab0d-fcdc7a4743b1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>1001194</value>
      <webElementGuid>c7555fd5-e8c8-4091-a0af-edb92f5d5f25</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>optionDivSelected</value>
      <webElementGuid>39955b73-0efb-48f0-beed-d94c904a3735</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>emp  01 </value>
      <webElementGuid>7d93c720-0c76-4317-9c7b-bfccd48b214a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;1001194&quot;)</value>
      <webElementGuid>d66d1b43-f9a8-42cf-a870-39448e489a57</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//div[@id='1001194']</value>
      <webElementGuid>56d61850-e685-467e-a4a0-4b3af653a729</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='ajax_listOfOptions']/div</value>
      <webElementGuid>e1d574b5-c821-479e-a6f5-d68e89c774ef</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)=concat('id(', '&quot;', '1001194', '&quot;', ')')])[1]/following::div[3]</value>
      <webElementGuid>8e3732cc-64dc-46c6-8620-f3a07093107a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='`'])[2]/following::div[4]</value>
      <webElementGuid>bdb7f186-0792-478a-8a93-b3e2683e272f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[8]/div</value>
      <webElementGuid>b352c843-8538-4357-88b4-2a2dfcdf159b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@id = '1001194' and (text() = 'emp  01 ' or . = 'emp  01 ')]</value>
      <webElementGuid>1f2fc1db-b37f-4188-a557-42bab07a26bf</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
