<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Good_DynamicRadioBox</name>
   <tag></tag>
   <elementGuidId>771b30e0-1c01-41fe-9cc0-d3b4103eba2b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#DynamicRadioBox</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='DynamicRadioBox']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>7dae8218-8266-4223-8d50-86f966febf50</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>radio</value>
      <webElementGuid>51f940a9-3020-4175-879d-3911ec5991b3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>DynamicRadioBox</value>
      <webElementGuid>159234d1-e1a2-4506-a36b-7402ef4f8a5f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>DynamicRadioBox</value>
      <webElementGuid>4b8a71a9-faef-4937-b336-4b7e1c9b6ab5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>Good</value>
      <webElementGuid>c63c0af0-fe26-47f2-b0e8-9722e914df06</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;modal-dialog-empxtrack&quot;)/div[@class=&quot;modal fade in&quot;]/div[@class=&quot;modal-dialog&quot;]/div[@class=&quot;modal-content&quot;]/div[@class=&quot;modal-body&quot;]/div[@class=&quot;col-md-12 popup_new&quot;]/div[@class=&quot;form-group&quot;]/label[1]/input[@id=&quot;DynamicRadioBox&quot;]</value>
      <webElementGuid>464cbb7e-8ea0-4808-b3d0-3199ab2e881b</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='DynamicRadioBox']</value>
      <webElementGuid>e105939f-e18d-4c87-8ee6-6b66525d271c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='modal-dialog-empxtrack']/div/div/div/div[2]/div/div[2]/label/input</value>
      <webElementGuid>5e06ab1d-944f-4bca-b558-8c9943c392d9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//label/input</value>
      <webElementGuid>9255742e-3783-48a5-8e44-7e137f2961a4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'radio' and @name = 'DynamicRadioBox' and @id = 'DynamicRadioBox']</value>
      <webElementGuid>5cb4f215-78ff-48d1-bd81-33e001667288</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
