<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_SuggestionArea</name>
   <tag></tag>
   <elementGuidId>181e90df-cae6-4565-9fbb-d49bcb33f349</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#empxtrack_feedback_subject_by_client</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='empxtrack_feedback_subject_by_client']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>45ccf899-f336-4785-b029-a4cd60a15628</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>eaa7f2b7-b8bb-4b52-b13b-9f4355df24d8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>empxtrack_feedback_subject_by_client</value>
      <webElementGuid>fbf6f6b8-4ee0-49c3-8489-c8bdf47b3cb3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>b5fbfc24-0945-4711-bb0e-ae441db2280d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Specify area</value>
      <webElementGuid>0e69dbd4-3d6b-4359-812b-9fbfbe232407</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;empxtrack_feedback_subject_by_client&quot;)</value>
      <webElementGuid>e99c94cd-8f0a-43a3-8d08-b736bc16e217</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='empxtrack_feedback_subject_by_client']</value>
      <webElementGuid>ee2a5f8d-5952-47c3-be4d-3790fcc62fde</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='modal-dialog-empxtrack']/div/div/div/div[2]/div/div/div/input</value>
      <webElementGuid>87f6dc30-d0a9-41da-ad8b-92b77ca75df8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/div/input</value>
      <webElementGuid>8a454ae3-a80d-48ed-b537-748cc2d25b78</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'empxtrack_feedback_subject_by_client' and @type = 'text' and @placeholder = 'Specify area']</value>
      <webElementGuid>ca3178e2-6b05-4664-8cae-f2d33781caaf</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
