<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_emp01rev</name>
   <tag></tag>
   <elementGuidId>5c858754-1e3c-44a0-a287-237c3c707b9f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#1001194</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='1001194']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>8a48e5c7-a710-4434-8e46-e4bcf1ed6b18</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>1001194</value>
      <webElementGuid>e51766da-5773-46b0-962c-56b8b11bfebe</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>optionDivSelected</value>
      <webElementGuid>40c0e648-ddd4-4a82-a0cc-5c6d8b4eb23a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>emp  01 </value>
      <webElementGuid>43cab7d9-7ab8-4c76-a6fb-fcfe888ac3dd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;1001194&quot;)</value>
      <webElementGuid>792ab552-8a16-4eb3-8f4c-fd38f7ab3b05</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//div[@id='1001194']</value>
      <webElementGuid>2c8fbee8-a459-4f95-afc3-ad715fa6b67c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='ajax_listOfOptions']/div</value>
      <webElementGuid>4d5c4919-6bc8-428b-a4d8-a2b9c6090a9b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)=concat('id(', '&quot;', '1001194', '&quot;', ')')])[1]/following::div[3]</value>
      <webElementGuid>eb32e6e4-7aab-4971-af8e-ce9e84662c9f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='`'])[2]/following::div[4]</value>
      <webElementGuid>bf8e6d6a-365a-43e5-842a-f07b1b917ca8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[8]/div</value>
      <webElementGuid>8bd08558-b7ab-4fb2-8e8c-38aa8ae792ac</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@id = '1001194' and (text() = 'emp  01 ' or . = 'emp  01 ')]</value>
      <webElementGuid>41e06179-6ea1-4aa3-a915-cf9bfef105e3</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
