<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>textarea_Message_chatMessageContent</name>
   <tag></tag>
   <elementGuidId>46189f08-76d4-4670-9e32-c20f7ba26ca4</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#chatMessageContent</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//textarea[@id='chatMessageContent']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>textarea</value>
      <webElementGuid>e38ed255-3b3b-433a-8137-d23710270998</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>chatMessageContent</value>
      <webElementGuid>19ee1bd1-b256-458f-9aba-354330083d43</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>cols</name>
      <type>Main</type>
      <value>80</value>
      <webElementGuid>f0785bbc-8da6-4b9b-8c66-d9826afc6068</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>rows</name>
      <type>Main</type>
      <value>3</value>
      <webElementGuid>cf29f7a4-4ef6-442a-9436-e5399934f47c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>8abfe88a-f465-40e1-86bd-cd16c6e8ea60</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;chatMessageContent&quot;)</value>
      <webElementGuid>b3d649bc-2625-4179-bae1-26752edc59d8</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//textarea[@id='chatMessageContent']</value>
      <webElementGuid>100cb65e-4fb0-43eb-8e99-6c581eea79f1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='modal-dialog-empxtrack']/div/div/div/div[2]/div[2]/div[4]/textarea</value>
      <webElementGuid>5a24521c-3094-4472-93be-e18d5d20a49f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//textarea</value>
      <webElementGuid>4981a583-fb43-4f64-8a9c-d5c0dcefb30b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//textarea[@id = 'chatMessageContent']</value>
      <webElementGuid>2c94bd52-e059-4f4f-a6a3-5c78b9d58631</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
