<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>textarea_ShareSuggestion</name>
   <tag></tag>
   <elementGuidId>6bf4e2b6-ad33-425c-9947-f1de27c6d2c0</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#empxtrack_feedback_by_client</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//textarea[@id='empxtrack_feedback_by_client']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>textarea</value>
      <webElementGuid>d24f6a5e-f9a9-46d2-8979-9643526a6d10</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>18979f5d-7c60-4733-9b1a-e57bba736718</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>empxtrack_feedback_by_client</value>
      <webElementGuid>1f492929-67bb-4e3f-996d-70380de05181</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Your suggestion</value>
      <webElementGuid>cdb04b42-9a76-4648-ac3f-14c8452f1c69</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;empxtrack_feedback_by_client&quot;)</value>
      <webElementGuid>3559bf14-2162-48bc-9584-e71bf57948e1</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//textarea[@id='empxtrack_feedback_by_client']</value>
      <webElementGuid>20fdd6e6-fa8e-429f-91c2-613563e133da</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='modal-dialog-empxtrack']/div/div/div/div[2]/div/div[2]/div/textarea</value>
      <webElementGuid>e562040f-84b8-4c8a-a7ec-5dad8a4aae8f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//textarea</value>
      <webElementGuid>c42e21b5-b1ef-405b-8d8a-9ada822fcd49</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//textarea[@id = 'empxtrack_feedback_by_client' and @placeholder = 'Your suggestion']</value>
      <webElementGuid>c54dce0c-565d-4698-9e94-2d39839fca35</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
