<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Due_29</name>
   <tag></tag>
   <elementGuidId>c7078bdb-f5aa-405f-b102-e15e6fe52f70</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#selectedEndDate</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//a[normalize-space()='29']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>90e67fdf-2fab-4715-82d5-b1e637da7f77</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>c3a955ba-41a6-4024-9ba3-5cbd06862547</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>selectedEndDate</value>
      <webElementGuid>3d212dee-365e-43e8-981d-5b0c11984010</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>date_selectedEndDate</value>
      <webElementGuid>0e0785ca-9a32-43dc-bdf9-6325d0f5361d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control cal hasDatepicker</value>
      <webElementGuid>7aa12485-e1e5-481a-ac3e-24428a52e86d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;selectedEndDate&quot;)</value>
      <webElementGuid>bd63d944-7112-43bd-b687-b02de5bd8ef4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/03 - Dashboard/3.1 - Event/Task/Page_Home page/iframe_Self services_homePageFrame</value>
      <webElementGuid>1b0a44c4-074f-426f-ae45-d4a4804c9fe5</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='selectedEndDate']</value>
      <webElementGuid>bd0622af-50bf-4310-9125-8fc91d822eea</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='eventSection']/div[2]/div/div/input</value>
      <webElementGuid>012769a7-f8b2-46a3-83d5-f8e8cbe5e0d3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div[2]/div[2]/div[2]/div/div/input</value>
      <webElementGuid>12244487-6b6b-43a6-a010-18a4c4d1a300</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = 'selectedEndDate' and @name = 'date_selectedEndDate']</value>
      <webElementGuid>7fe5c143-0e08-4b2c-8778-fc9b55329ea7</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
