<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Subject_subject</name>
   <tag></tag>
   <elementGuidId>b9aac061-90f5-4dcb-bad2-91af4ef60abc</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//*[@type = 'text' and @id = 'subject' and @ref_element = 'Object Repository/03 - Dashboard/3.1 - Event/Task/Page_Home page/iframe_Self services_homePageFrame']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#subject</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='subject']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>5862404b-1bcd-409a-a1fa-d709efd972e3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>09bfe3a9-8b07-4333-a29f-676ae5a06811</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>subject</value>
      <webElementGuid>370260fe-ab3a-4652-b74b-bdab96f4b5c9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>390ad535-42b2-4117-819b-56692350b859</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;subject&quot;)</value>
      <webElementGuid>e336656c-203c-4938-bdc9-a6ef43878d5d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/03 - Dashboard/3.1 - Event/Task/Page_Home page/iframe_Self services_homePageFrame</value>
      <webElementGuid>d4ad14ad-4ac8-4695-9fc0-7b1c65dd60d7</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='subject']</value>
      <webElementGuid>b399f4e0-d6c7-45d0-9a39-5d4641135296</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='eventSection']/div/div/input</value>
      <webElementGuid>9a5d0437-c8d3-4aa3-987e-98b1b4b4af74</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div[2]/div/div/input</value>
      <webElementGuid>9f09eb54-f362-4b65-8ae2-0c63684f0505</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = 'subject']</value>
      <webElementGuid>bd0b356f-3b92-4748-a03f-3ddd97c1d1e6</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
